Repository ponylang/ponyc, pull requests merged in 2018-03, with the labels that each got.

#2513 Add full'ish support for network socket get & set options
  examples/under_pressure/main.pony
  packages/builtin/platform.pony
  packages/net/ossocket.pony
  packages/net/ossockopt.pony
  packages/net/tcp_connection.pony
  packages/net/udp_socket.pony
  src/libponyc/codegen/genopt.cc
  src/libponyc/codegen/genopt.h
  src/libponyc/codegen/genprim.c
  src/libponyc/pkg/buildflagset.c
  src/libponyc/pkg/platformfuns.c
  src/libponyc/pkg/platformfuns.h
  src/libponyrt/lang/socket.c
Labels: changelog - added, enhancement: 4 - in progress

#2561 Fix two race conditions where an ASIO wakeup notifications can be lost
  src/libponyc/options/options.c
  src/libponyrt/asio/epoll.c
  src/libponyrt/asio/iocp.c
  src/libponyrt/asio/kqueue.c
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/start.c
Labels: changelog - fixed

#2574 Always unsubscribe process_monitor fds before closing them (#2529)
  packages/process/process_monitor.pony
Labels: changelog - fixed

#2578 New Ponybench API (RFC 52)
  examples/ponybench/main.pony
  packages/ponybench/_aggregator.pony
  packages/ponybench/_auto_bench.pony
  packages/ponybench/_bench.pony
  packages/ponybench/_bench_async.pony
  packages/ponybench/_output_manager.pony
  packages/ponybench/_results.pony
  packages/ponybench/_runner.pony
  packages/ponybench/_test.pony
  packages/ponybench/benchmark.pony
  packages/ponybench/pony_bench.pony
  packages/stdlib/_test.pony
Labels: changelog - changed

#2586 Fix extracting docstring from constructors
  src/libponyc/pass/sugar.c
  test/libponyc/sugar.cc
Labels: changelog - fixed

#2592 Partially mitigate LLVM's infinite loops bug
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/codegen.h
  src/libponyc/codegen/gentype.c
  src/libponyc/codegen/host.cc
Labels: changelog - fixed

#2593 Fix tracing of boxed tuples through interfaces
  src/libponyc/codegen/genfun.c
  src/libponyc/codegen/gentrace.c
  src/libponyc/codegen/gentype.c
  test/libponyc/codegen_trace.cc
Labels: changelog - fixed

#2594 Update the Windows build to support the latest Visual C++ Build Tools
  README.md
  wscript
Labels: changelog - fixed

#2598 Properly report type parameter capability errors
  src/libponyc/pass/flatten.c
  test/libponyc/flatten.cc
Labels: changelog - fixed

#2585 Allow recovering at most one element of a tuple to mutable capability.
  src/libponyc/type/alias.c
  test/libponyc/recover.cc
Labels: changelog - added

#2611 Handle EAGAIN errors on socket operations
  src/libponyrt/lang/socket.c
Labels: changelog - fixed

#2612 Ensure ASIO thread cannot be stopped prematurely
  src/libponyrt/asio/asio.c
  src/libponyrt/asio/asio.h
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
Labels: changelog - fixed

#2603 Fix compiler crash related to array inference.
  src/libponyc/expr/array.c
  test/libponyc/badpony.cc
Labels: changelog - fixed

#2588 Add field docstrings to public fields of stdlib entities
  packages/builtin/env.pony
  packages/builtin/stdin.pony
  packages/files/directory.pony
  packages/files/file.pony
  packages/files/file_info.pony
  packages/files/file_mode.pony
  packages/files/file_path.pony
  packages/json/json_doc.pony
  packages/json/json_type.pony
  packages/net/http/_client_connection.pony
  packages/net/http/_http_parser.pony
  packages/net/http/client.pony
  packages/net/http/payload.pony
  packages/net/http/status.pony
  packages/net/http/url.pony
  packages/net/net_address.pony
  packages/options/options.pony
  packages/ponybench/benchmark.pony
  packages/ponytest/test_helper.pony
Labels: project documentation

#2616 Fix off-by-one error in String.cstring
  packages/builtin/string.pony
Labels: changelog - fixed
