Repository ponylang/ponyc, pull requests merged in 2018-11, with the labels that each got.

#2916 Link to libexecinfo on BSD always, not just in a debug compiler
  src/libponyc/codegen/genexe.c
Labels: changelog - fixed

#2503 Downgrade iso and trn to ref when replacing this in a box method.
  CHANGELOG.md
  src/libponyc/type/lookup.c
  test/libponyc/badpony.cc
Labels: bug: 4 - in progress, triggers release

#2660 Fix unsafe cases in capability subtyping implementation
  packages/collections/map.pony
  packages/itertools/iter.pony
  src/libponyc/expr/lambda.c
  src/libponyc/type/alias.c
  src/libponyc/type/cap.c
  src/libponyc/type/matchtype.c
  src/libponyc/type/subtype.c
  test/libponyc/cap.cc
Labels: changelog - fixed

#2939 Make _SignedInteger and _UnsignedInteger public
  packages/builtin/_partial_arithmetic.pony
  packages/builtin/real.pony
  packages/builtin/signed.pony
  packages/builtin/unsigned.pony
Labels: changelog - added

#2942 Add whitespace between multiple args on cli help output
  packages/cli/_test.pony
  packages/cli/command_spec.pony
Labels: changelog - fixed

#2943 Add information what to install from Visual C++ Build Tools 2017
  README.md
Labels: windows
