Repository ponylang/ponyc, pull requests merged in 2018-10, with the labels that each got.

#2893 Fix installation of libponyrt.bc on Linux
  Makefile
Labels: changelog - fixed

#2892 Correctly handle modifier keys for TTY stdin on Windows
  src/libponyrt/lang/stdfd.c
Labels: changelog - fixed

#2889 Add ability to get iso array from an iso string.
  packages/builtin/string.pony
Labels: changelog - added

#2888 Rename mod and related operators to rem
  packages/builtin/_partial_arithmetic.pony
  packages/builtin/real.pony
  packages/builtin/signed.pony
  packages/builtin/unsigned.pony
  packages/builtin_test/_test.pony
  src/libponyc/ast/lexer.c
  src/libponyc/ast/parser.c
  src/libponyc/ast/token.h
  src/libponyc/ast/treecheckdef.h
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/codegen.h
  src/libponyc/codegen/gencall.c
  src/libponyc/codegen/genoperator.c
  src/libponyc/codegen/genoperator.h
  src/libponyc/expr/literal.c
  src/libponyc/pass/sugar.c
  src/libponyc/pass/syntax.c
  test/libponyc/sugar.cc
Labels: changelog - changed

#2890 `buffered` performance improvements and bug fix
  packages/buffered/_test.pony
  packages/buffered/benchmarks/main.pony
  packages/buffered/reader.pony
  packages/buffered/writer.pony
  packages/builtin/array.pony
  packages/builtin/real.pony
  packages/builtin/signed.pony
  packages/builtin/unsigned.pony
  packages/files/_test.pony
  packages/net/ossocket.pony
Labels: changelog - fixed

#2896 Fix invalid allocation bug in runtime that allows for segfaults
  src/libponyrt/mem/pool.c
Labels: changelog - fixed

#2898 Add before/after iteration hooks to ponybench
  packages/buffered/benchmarks/main.pony
  packages/ponybench/_runner.pony
  packages/ponybench/benchmark.pony
Labels: changelog - changed

#2927 Correct README.md link to AppImage packaging location
  README.md
Labels: changelog - fixed

#2928 [docgen] use basename as program package name
  src/libponyc/pkg/package.c
Labels: project documentation

#2919 Install libdtrace_probes.a into the right directory on FreeBSD
  Makefile-ponyc
Labels: changelog - fixed
