Repository ponylang/ponyc, pull requests merged in 2018-09, with the labels that each got.

#2872 Fix losing data when reading from STDIN.
  packages/builtin/stdin.pony
Labels: changelog - fixed

#2879 Fix building on Windows in a directory with spaces in its name
  wscript
Labels: changelog - fixed, windows

#2880 Update our copy of `waf` for building on Windows
  waf
Labels: windows

#2877 Fix compilation warning on windows.
  src/libponyc/codegen/gendebug.cc
Labels: changelog - fixed, windows

#2882 Add divc method to integer types
  packages/builtin/_partial_arithmetic.pony
  packages/builtin/real.pony
  packages/builtin/signed.pony
  packages/builtin/unsigned.pony
  packages/builtin_test/_test.pony
Labels: changelog - added

#2883 Add modc method to integer types
  packages/builtin/_partial_arithmetic.pony
  packages/builtin/real.pony
  packages/builtin/signed.pony
  packages/builtin/unsigned.pony
  packages/builtin_test/_test.pony
Labels: changelog - added
