Repository ponylang/ponyc, pull requests merged in 2018-08, with the labels that each got.

#2852 Use RLIMIT_STACK's current limit for Pthreads stack size if it is sane
  src/libponyrt/platform/threads.c
Labels: changelog - changed

#2853 Fix skipped try-then clauses on return, break and continue statements
  src/libponyc/ast/ast.c
  src/libponyc/codegen/gencontrol.c
  test/libponyc/codegen.cc
Labels: changelog - fixed

#2862 Fix `files/Path.clean()` not correctly handling multiple `..`
  packages/files/_test.pony
  packages/files/path.pony
Labels: changelog - fixed

#2860 Fix validation of provides lists of object literals.
  src/libponyc/expr/lambda.c
  src/libponyc/pass/flatten.c
  src/libponyc/pass/syntax.c
  test/libponyc/badpony.cc
  test/libponyc/object.cc
Labels: changelog - fixed

#2823 Added OpenBSD support.
  Makefile
  README.md
  lib/gbenchmark/src/internal_macros.h
  lib/gbenchmark/src/sysinfo.cc
  lib/gbenchmark/src/timers.cc
  packages/builtin/platform.pony
  src/common/paths.h
  src/common/platform.h
  src/libponyc/codegen/genexe.c
  src/libponyc/codegen/genopt.cc
  src/libponyc/codegen/genopt.h
  src/libponyc/codegen/genprim.c
  src/libponyc/pass/pass.h
  src/libponyc/pkg/buildflagset.c
  src/libponyc/pkg/package.c
  src/libponyc/pkg/platformfuns.c
  src/libponyc/pkg/platformfuns.h
  src/libponyc/platform/paths.c
  src/libponyrt/lang/socket.c
  src/libponyrt/mem/alloc.c
  src/libponyrt/platform/ponyassert.c
  src/libponyrt/sched/cpu.c
  src/ponyc/main.c
Labels: changelog - added

#2865 [RFC 58] Add partial arithmetic for integer types
  packages/builtin/_partial_arithmetic.pony
  packages/builtin/real.pony
  packages/builtin/signed.pony
  packages/builtin/unsigned.pony
  packages/builtin_test/_test.pony
  src/libponyc/ast/bnfprint.c
  src/libponyc/ast/lexer.c
  src/libponyc/pass/sugar.c
  test/libponyc/lexer.cc
  test/libponyc/verify.cc
Labels: changelog - added
