Repository ponylang/ponyc, pull requests merged in 2018-02, with the labels that each got.

#2542 Remove case functions
  packages/debug/debug.pony
  pony.g
  src/libponyc/ast/parser.c
  src/libponyc/ast/treecheckdef.h
  src/libponyc/expr/lambda.c
  src/libponyc/pass/casemethod.c
  src/libponyc/pass/casemethod.h
  src/libponyc/pass/sugar.c
  src/libponyc/pass/traits.c
  test/libponyc/dontcare.cc
  test/libponyc/scope.cc
  test/libponyc/sugar.cc
Labels: changelog - changed

#2499 Forbid impossible pattern matching on generic capabilities
  src/libponyc/type/cap.c
  src/libponyc/type/cap.h
  src/libponyc/type/matchtype.c
  test/libponyc/matchtype.cc
Labels: changelog - changed

#2550 Correctly typecheck FFI arguments with regard to aliasing
  src/libponyc/expr/ffi.c
  test/libponyc/ffi.cc
Labels: changelog - fixed

#2535 Allow user defined help string at CommandSpec.add_help()
  packages/cli/command_spec.pony
Labels: changelog - added

#2543 [RFC 50] add member docstrings
  pony.g
  src/libponyc/ast/parser.c
  src/libponyc/ast/treecheckdef.h
  src/libponyc/expr/lambda.c
  src/libponyc/pass/docgen.c
  test/libponyc/parse_entity.cc
Labels: changelog - added, project documentation

#2566 Add basic compiler plugins
  src/common/platform.h
  src/libponyc/ast/ast.c
  src/libponyc/ast/ast.h
  src/libponyc/codegen/genexe.c
  src/libponyc/codegen/genlib.c
  src/libponyc/options/options.c
  src/libponyc/pass/pass.c
  src/libponyc/pass/pass.h
  src/libponyc/pkg/package.c
  src/libponyc/pkg/package.h
  src/libponyc/plugin/plugin.c
  src/libponyc/plugin/plugin.h
  src/libponyc/reach/reach.h
  src/ponyc/main.c
Labels: changelog - added

#2568 Make the File.open constructor use read-only mode (Issue #2567)
  packages/files/file.pony
Labels: changelog - fixed

#2552 Fix compiler crash in alternate name suggestion logic (issue #2508).
  src/libponyc/pass/refer.c
  test/libponyc/suggest_alt_name.cc
Labels: changelog - fixed
