Repository ponylang/ponyc, pull requests merged in 2018-07, with the labels that each got.

#2801 Make dynamic scheduler scaling more robust and configurable
  src/libponyc/options/options.c
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
  src/libponyrt/sched/start.c
Labels: changelog - added

#2826 Add libexecinfo to debug builds for BSD
  Makefile
  src/libponyc/codegen/genexe.c
Labels: bug: 4 - in progress, changelog - fixed

#2840 Fix array and string trim_in_place allocation bounds check
  packages/builtin/array.pony
  packages/builtin/string.pony
  packages/builtin_test/_test.pony
Labels: changelog - fixed, triggers release
