Repository ponylang/ponyc, pull requests merged in 2018-05, with the labels that each got.

#2631 Add mechanism to register (noisy) signal handler
  packages/signals/signal_handler.pony
Labels: changelog - added

#2656 Fix File.valid() and clarify File behavior in error cases
  .ci-dockerfiles/alpine-llvm-3.9.1/Dockerfile
  .ci-dockerfiles/alpine-llvm-3.9.1/README.md
  .ci-dockerfiles/llvm-3.9.1/Dockerfile
  .ci-dockerfiles/llvm-3.9.1/README.md
  .ci-dockerfiles/llvm-4.0.1/Dockerfile
  .ci-dockerfiles/llvm-4.0.1/README.md
  .ci-dockerfiles/llvm-5.0.1/Dockerfile
  .ci-dockerfiles/llvm-5.0.1/README.md
  .ci-dockerfiles/llvm-6.0.0/Dockerfile
  .ci-dockerfiles/llvm-6.0.0/README.md
  .ci-dockerfiles/openssl-1.1.0/Dockerfile
  .ci-dockerfiles/openssl-1.1.0/README.md
  .ci-dockerfiles/shellcheck/README.md
  .circleci/config.yml
  packages/files/_test.pony
  packages/files/file.pony
Labels: changelog - fixed

#2645 Add addc, subc and mulc functions to I128 and U128
  packages/builtin/real.pony
  packages/builtin/signed.pony
  packages/builtin/unsigned.pony
  packages/builtin_test/_test.pony
Labels: changelog - added

#2692 Avoid flattening arrow to type param, fixing typechecking when reified with another type param.
  src/libponyc/type/typeparam.c
  src/libponyc/type/viewpoint.c
  test/libponyc/type_check_subtype.cc
Labels: changelog - fixed

#2697 Change directory.open_file() to use readonly open
  packages/files/_test.pony
  packages/files/directory.pony
Labels: changelog - fixed

#2693 Do not use llvm.smul.with.overflow.i64 anymore
  packages/builtin/signed.pony
Labels: LLVM, changelog - fixed

#2698 Compute File.writeable based on FileWrite instead of FileRead.
  packages/files/_test.pony
  packages/files/file.pony
Labels: changelog - fixed

#2702 Enable virtual terminal color output on Windows.
  src/libponyrt/lang/stdfd.c
Labels: changelog - fixed, windows

#2704 Fix File.flush return value for case of zero bytes to flush.
  packages/files/_test.pony
  packages/files/file.pony
Labels: changelog - fixed

#2703 Fix temporary file from test not getting deleted on Windows
  packages/files/_test.pony
Labels: windows

#2706 Incorrect rstrip handling of multibyte characters
  packages/builtin/string.pony
  packages/builtin_test/_test.pony
Labels: changelog - fixed

#2717 Relax ProcessMonitor checks for execute bits
  packages/process/_test.pony
  packages/process/process_monitor.pony
Labels: changelog - fixed

#2725 Only enable mcx16 for gcc for x86_64 targets
  Makefile
  src/libponyc/codegen/genexe.c
Labels: changelog - fixed
