Repository ponylang/ponyc, pull requests merged in 2018-06, with the labels that each got.

#2721 Fix CommandSpec without args and help
  packages/cli/_test.pony
  packages/cli/cli.pony
  packages/cli/command_parser.pony
  packages/cli/command_spec.pony
  packages/stdlib/_test.pony
Labels: changelog - fixed

#2738 Fix compiler crash related to union types with duplicate members.
  src/libponyc/pass/expr.c
  test/libponyc/codegen.cc
Labels: changelog - fixed

#2745 Fix memory overflow when allocating CPUs when numa is enabled
  src/libponyrt/sched/cpu.c
Labels: changelog - fixed, triggers release

#2744 Fix incorrect disposable/destroyed epoll resubscribe handling
  src/libponyrt/asio/epoll.c
Labels: changelog - fixed

#2751 Fix performance related to dynamic scheduler scaling
  src/libponyrt/sched/scheduler.c
Labels: changelog - fixed

#2754 Fix `collections/persistent/Lists.from()` to return elements in the correct order
  packages/collections/persistent/_test.pony
  packages/collections/persistent/list.pony
Labels: changelog - fixed

#2757 Fix compiler segfault caused by dead code removal of tupled variables
  src/libponyc/codegen/genreference.c
  test/libponyc/codegen.cc
Labels: changelog - fixed

#2756 RFC 56: Make buffered.reader.line return String iso^
  packages/buffered/reader.pony
  packages/net/http/_http_parser.pony
  packages/net/http/_test.pony
  packages/term/readline.pony
Labels: changelog - changed

#2770 Fix Promise bug where join() element's reject doesn't reject the entire join
  packages/promises/_test.pony
  packages/promises/promise.pony
Labels: changelog - fixed

#2763 Fix incorrect tuple handling
  src/libponyc/codegen/genreference.c
  test/libponyc/codegen.cc
Labels: changelog - fixed

#2771 Fix File.writev and File.flush in cases where the IO vector exceeds IOV_MAX.
  packages/files/_test.pony
  packages/files/file.pony
Labels: changelog - fixed

#2775 Fix GC-safety issue with writev pointers in File.
  packages/files/file.pony
Labels: changelog - fixed

#2781 Fix incorrect disposable/destroyed epoll resubscribe handling
  src/libponyrt/asio/epoll.c
Labels: changelog - fixed

#2786 Fix repeat loop symbol tracking to allow more valid cases.
  src/libponyc/ast/ast.c
  src/libponyc/ast/ast.h
  src/libponyc/ast/parser.c
  src/libponyc/ast/treecheckdef.h
  src/libponyc/pass/refer.c
  test/libponyc/refer.cc
Labels: changelog - fixed

#2791 Fix some edge cases in code generation for loops that jump away.
  src/libponyc/codegen/gencontrol.c
  test/libponyc/codegen.cc
Labels: changelog - fixed

#2734 Change NetAddress class to hide its fields behind functions, fixing cross-platform compatibility.
  packages/net/net_address.pony
  src/libponyrt/lang/socket.c
Labels: changelog - changed

#2747 Change refcap of JsonDoc to ref for better usability
  packages/json/json.pony
  packages/json/json_doc.pony
  packages/json/json_type.pony
Labels: changelog - changed

#2795 [RFC 55] Remove package net/http from stdlib
  examples/httpget/.gitignore
  examples/httpget/cacert.pem
  examples/httpget/httpget.pony
  examples/httpserver/.gitignore
  examples/httpserver/httpserver.pony
  packages/net/http/_client_conn_handler.pony
  packages/net/http/_client_connection.pony
  packages/net/http/_host_service.pony
  packages/net/http/_http_parser.pony
  packages/net/http/_server_conn_handler.pony
  packages/net/http/_server_connection.pony
  packages/net/http/_server_listener.pony
  packages/net/http/_test.pony
  packages/net/http/client.pony
  packages/net/http/common_log.pony
  packages/net/http/contents_log.pony
  packages/net/http/discard_log.pony
  packages/net/http/http_handler.pony
  packages/net/http/http_session.pony
  packages/net/http/mimetypes.pony
  packages/net/http/payload.pony
  packages/net/http/server.pony
  packages/net/http/server_notify.pony
  packages/net/http/status.pony
  packages/net/http/url.pony
  packages/net/http/url_encode.pony
  packages/stdlib/_test.pony
Labels: changelog - changed

#2785 Do not set File._errno when reading less than requested bytes.
  packages/files/_test.pony
  packages/files/file.pony
Labels: changelog - fixed

#2709 Run cycle detector every N ms based on timer
  examples/dtrace/mbox-size-all-actor-messages.d
  examples/dtrace/telemetry.d
  examples/systemtap/telemetry.stp
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/genexe.c
  src/libponyc/options/options.c
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/gc/cycle.h
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/start.c
  test/libponyc/codegen.cc
Labels: changelog - changed, needs discussion during sync

#2811 Always use "binary" mode when opening files on Windows.
  src/libponyrt/lang/directory.c
Labels: changelog - fixed
