Repository ponylang/ponyc, pull requests merged in 2019-02, with the labels that each got.

#2997 [RFC 61] Add Modulo Operator (and floored division)
  packages/builtin/_arithmetic.pony
  packages/builtin/_partial_arithmetic.pony
  packages/builtin/float.pony
  packages/builtin/real.pony
  packages/builtin/signed.pony
  packages/builtin/unsigned.pony
  packages/builtin_test/_test.pony
  pony.g
  src/libponyc/ast/lexer.c
  src/libponyc/ast/parser.c
  src/libponyc/ast/token.h
  src/libponyc/ast/treecheckdef.h
  src/libponyc/pass/sugar.c
  src/libponyc/pass/syntax.c
  test/libponyc/lexer.cc
Labels: changelog - added

#3010 Revert to LLVM 3.9.1 as the default for Windows builds.
  wscript
Labels: LLVM, windows

#3025 Use heap-to-stack workaround for Windows
  src/libponyc/codegen/genopt.cc
  src/libponyc/options/options.c
  src/libponyrt/sched/start.c
  wscript
Labels: LLVM, windows

#3018 Fix default arguments not being displayed correctly in generated docs
  src/libponyc/pass/docgen.c
Labels: changelog - fixed

#3024 Change default to disable pinning of scheduler threads to CPU cores
  src/libponyc/options/options.c
  src/libponyrt/sched/start.c
Labels: DO NOT MERGE, changelog - changed

#3019 Windows implementation of Process and Pipe.
  packages/process/_pipe.pony
  packages/process/_process.pony
  packages/process/_test.pony
  packages/process/process_monitor.pony
  src/libponyrt/lang/process.c
  src/libponyrt/lang/process.h
  src/libponyrt/sched/start.c
Labels: changelog - added

#3020 Change `--ponyminthreads` default to `0`
  src/libponyc/options/options.c
  src/libponyrt/sched/start.c
Labels: changelog - changed

#3032 Make LLVM 7.0.1 the default for Windows builds and releases.
  .appveyor.yml
  wscript
Labels: LLVM, windows

#3038 Only build LLVM 7.0.1 for Windows CI.
  .appveyor.yml
Labels: LLVM, windows

#3039 Add FreeBSD 12 with LLVM 7 as supported platform
  .appveyor.yml
  .ci-dockerfiles/cross-llvm-3.9.1-freebsd11-x86_64/Dockerfile
  .ci-dockerfiles/cross-llvm-3.9.1-freebsd11-x86_64/README.md
  .cirrus.yml
  .travis.yml
  Makefile-ponyc
  README.md
Labels: changelog - added
