Repository ponylang/ponyc, pull requests merged in 2019-04, with the labels that each got.

#3129 Fix error reporting for non-sendable lambda captures.
  src/libponyc/pass/flatten.c
  test/libponyc/flatten.cc
Labels: changelog - fixed

#3127 Avoid busy loop when waiting for input on stdin.
  src/libponyrt/lang/stdfd.c
Labels: changelog - fixed

#3136 Don't turn off Epoll OneShot when resubscribing to OneShot events
  src/libponyrt/asio/epoll.c
Labels: changelog - fixed, triggers release

#3141 Allow building and running `ponyc` with Visual Studio 2019
  README.md
  waf
  wscript
Labels: changelog - added, windows
