Repository ponylang/ponyc, pull requests merged in 2019-07, with the labels that each got.

#3218 Remove `regex` package from standard library
  .ci-dockerfiles/alpine-llvm-5/Dockerfile
  .ci-dockerfiles/alpine/Dockerfile
  .ci-dockerfiles/centos7-llvm-3.9.1/Dockerfile
  .ci-dockerfiles/centos7/Dockerfile
  .ci-dockerfiles/cross-llvm-7.0.1-aarch64/Dockerfile
  .ci-dockerfiles/cross-llvm-7.0.1-arm/Dockerfile
  .ci-dockerfiles/cross-llvm-7.0.1-armhf/Dockerfile
  .ci-dockerfiles/cross-llvm-7.0.1-i686/Dockerfile
  .ci-dockerfiles/openssl-1.1.0/Dockerfile
  .ci-dockerfiles/ubuntu-16.04-base/Dockerfile
  .ci-dockerfiles/ubuntu-18.04-base/Dockerfile
  .ci-dockerfiles/ubuntu/Dockerfile
  .cirrus.yml
  .dockerhub/alpine/Dockerfile
  .packaging/deb/control
  .packaging/rpm/ponyc.spec
  .travis_commands.bash
  .travis_install.bash
  .travis_script.bash
  CHANGELOG.md
  Dockerfile
  README.md
  packages/regex/_test.pony
  packages/regex/match.pony
  packages/regex/match_iterator.pony
  packages/regex/regex.pony
  packages/stdlib/_test.pony
Labels: DO NOT MERGE

#3224 CI test. Ignore.
  .circleci/config.yml
Labels: DO NOT MERGE

#3229 Fix `which dtrace` path check
  CHANGELOG.md
  Makefile-ponyc
Labels: changelog - fixed

#3254 Fix segfault due to Cycle Detector viewref inconsistency
  CHANGELOG.md
  src/libponyrt/gc/cycle.c
Labels: triggers release
