Repository ponylang/ponyc, pull requests merged in 2019-03, with the labels that each got.

#3043 make String.f32() and String.f64() partial
  packages/builtin/string.pony
  packages/builtin_test/_test.pony
  packages/cli/command_spec.pony
  packages/options/options.pony
  src/libponyrt/lang/directory.c
Labels: changelog - changed

#3050 Update TCPConnection docs around local and remote addresses
  packages/net/tcp_connection.pony
Labels: changelog - fixed

#3076 Stop supporting Ubuntu Trusty
  .bintray_deb.bash
  .ci-dockerfiles/deb-builder/Dockerfile
  .ci-dockerfiles/deb-builder/README.md
  .packaging/deb/rules
  .travis_commands.bash
  README.md
Labels: changelog - changed

#3077 Stop trying to be clever when finding user's LLVM installation
  .cirrus.yml
  Makefile-ponyc
Labels: changelog - changed

#3079 Upgrade Docker image to use LLVM 7.0.1
  Dockerfile
Labels: changelog - changed

#3086 Fixed issue with ponyc not being able to find Visual Studio Build Tools in non-standard locations.
  src/libponyc/platform/vcvars.c
Labels: changelog - fixed, windows

#3100 Stop Supporting Ubuntu Artful
  .ci-dockerfiles/deb-builder/README.md
  .packaging/deb/rules
  .travis.yml
  .travis_commands.bash
Labels: changelog - changed

#3102 Ensure methods reached through a union are detected as reachable.
  src/libponyc/reach/reach.c
  test/libponyc/reach.cc
Labels: changelog - fixed, triggers release
