Repository ponylang/ponyc, pull requests merged in 2020-05, with the labels that each got.

#3532 Update ProcessMonitor errors to contain error messages
  packages/process/_process.pony
  packages/process/_test.pony
  packages/process/process_error.pony
  packages/process/process_monitor.pony
  src/libponyrt/lang/process.c
  src/libponyrt/lang/process.h
Labels: changelog - changed

#3538 Fix unneeded dependency on Linux glibc systems
  lib/CMakeLists.txt
Labels: changelog - fixed, triggers release

#3541 Fix CommandParser incorrectly handling multiple end-of-option delimiters
  packages/cli/_test.pony
  packages/cli/command_parser.pony
Labels: changelog - fixed

#3419 Ensure non-blocking process wait and correctly report process exit status
  CHANGELOG.md
  packages/process/_process.pony
  packages/process/_test.pony
  packages/process/_test.sh
  packages/process/process_monitor.pony
  packages/process/process_notify.pony
  src/libponyrt/CMakeLists.txt
  src/libponyrt/lang/directory.c
  src/libponyrt/lang/errno.c
  src/libponyrt/lang/errno.h
  src/libponyrt/lang/process.c
  src/libponyrt/lang/process.h
Labels: changelog - fixed

#3545 Add Ubuntu18.04 builds
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu18.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu18.04-builder/build-and-push.bash
  .cirrus.yml
Labels: changelog - added

#3552 Fix atomics usage related to actor muting for ARM
  src/libponyrt/actor/actor.c
  src/libponyrt/sched/scheduler.c
Labels: changelog - fixed

#3556 Rename FreeBSD artifacts
  .ci-scripts/x86-64-unknown-freebsd-12.1-nightly.bash
  .ci-scripts/x86-64-unknown-freebsd-12.1-release.bash
  .cirrus.yml
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - changed

#3554 Switch Linux nightly and release config to matrix
  .cirrus.yml
Labels: DO NOT MERGE

#3559 Fix incorrect Windows process waiting
  src/libponyrt/lang/process.c
Labels: changelog - fixed
