Repository ponylang/ponyc, pull requests merged in 2020-09, with the labels that each got.

#3632 Add prebuilt ponyc binaries for Ubuntu 20.04
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/prebuilt-ubuntu20.04.md
Labels: changelog - added

#3639 Make Range.next() partial
  .release-notes/3639.md
  packages/collections/range.pony
Labels: changelog - changed

#3649 Speed up cycle detector reaping some actors
  .release-notes/dipin-cd-patch.md
  src/libponyrt/actor/actor.c
  src/libponyrt/gc/cycle.c
Labels: changelog - fixed

#3650 Prevent compiler crashes on certain `consume` expressions
  .release-notes/3650.md
  src/libponyc/pass/refer.c
  src/libponyc/pass/syntax.c
  test/libponyc/refer.cc
Labels: changelog - fixed, do not merge

#3657 Fix soundness problem with Array.chop
  .release-notes/3657.md
  packages/builtin/array.pony
Labels: changelog - fixed

#3654 Allow for building on DragonFlyBSD again
  benchmark/libponyc/CMakeLists.txt
  benchmark/libponyrt/CMakeLists.txt
  src/libponyrt/CMakeLists.txt
  src/ponyc/CMakeLists.txt
  test/libponyc/CMakeLists.txt
  test/libponyrt/CMakeLists.txt
Labels: changelog - fixed

#3653 Improvements to garbage collection of short-lived actors
  .release-notes/3653.md
  examples/dtrace/mbox-size-all-actor-messages.d
  examples/dtrace/telemetry.d
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/gencall.c
  src/libponyc/codegen/gencall.h
  src/libponyc/codegen/genexe.c
  src/libponyc/codegen/genfun.c
  src/libponyc/pass/expr.c
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/gc/cycle.h
  src/libponyrt/pony.h
Labels: changelog - added

#2523 Don't reschedule unmuted actors with no work
  src/libponyrt/sched/scheduler.c
Labels: do not merge

#3666 Fix race condition in cycle detector block sent handling
  .release-notes/cd-double-free.md
  src/libponyrt/actor/actor.c
Labels: changelog - fixed

#3667 Fix race conditions that can lead to a segfault
  .release-notes/3667.md
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/messageq.c
  src/libponyrt/actor/messageq.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/sched/scheduler.c
Labels: changelog - fixed
