Repository ponylang/ponyc, pull requests merged in 2020-07, with the labels that each got.

#3587 Added vs2019 preview support for building ponyc
  make.ps1
Labels: changelog - added

#3586 Fix with expressions using tuple destructuring.
  src/libponyc/pass/sugar.c
  test/libponyc/sugar.cc
Labels: changelog - fixed

#3589 Fix typeparam check endless recursion
  src/libponyc/type/typeparam.c
Labels: changelog - fixed

#3588 Force removing read-only files on Windows with `FilePath.remove()`
  packages/files/_test.pony
  packages/files/file_path.pony
Labels: changelog - fixed

#3591 Change trn->trn to box to fix a soundness hole
  src/libponyc/type/cap.c
  test/libponyc/cap.cc
Labels: changelog - changed

#3597 Add LogLevel as argument to LogFormatter
  packages/logger/_test.pony
  packages/logger/logger.pony
Labels: changelog - changed

#3603 Implement RFC 66: Iter maybe
  packages/itertools/_test.pony
  packages/itertools/iter.pony
Labels: changelog - added
