Repository ponylang/ponyc, pull requests merged in 2020-04, with the labels that each got.

#3492 Build Docker images for windows builds
  .dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
  .dockerfiles/latest/x86-64-pc-windows-msvc/build-and-push.ps1
  .dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
  .dockerfiles/release/x86-64-pc-windows-msvc/build-and-push.ps1
  .github/workflows/handle-external-events.yml
  .github/workflows/pr.yml
Labels: changelog - added

#3487 Added support for VS Preview
  src/libponyc/platform/vcvars.c
Labels: changelog - added

#3495 Update supported FreeBSD version to 12.1
  .cirrus.yml
Labels: changelog - changed

#3493 Update Windows build docker image to use an image on DockerHub.
  .ci-dockerfiles/windowsservercore/Dockerfile
  .ci-dockerfiles/windowsservercore/README.md
  .ci-dockerfiles/x86-64-pc-windows-msvc-builder/Dockerfile
  .ci-dockerfiles/x86-64-pc-windows-msvc-builder/README.md
  .ci-dockerfiles/x86-64-pc-windows-msvc-builder/build-and-push.ps1
  .cirrus.yml
Labels: windows

#3497 Add git to Windows ponyc docker images
  .dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
  .dockerfiles/latest/x86-64-pc-windows-msvc/git.ini
  .dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
  .dockerfiles/release/x86-64-pc-windows-msvc/git.ini
  .github/workflows/pr.yml
Labels: windows

#3502 Add nightly FreeBSD 12.1 builds
  .ci-scripts/x86-64-unknown-freebsd12.1-nightly.bash
  .cirrus.yml
Labels: changelog - added

#3506 Make clang our default compiler on Linux, macOS, and FreeBSD
  BUILD.md
  INSTALL.md
  Makefile
Labels: changelog - changed

#3507 schedule the cycle detector with higher priority using the inject queue
  src/libponyrt/actor/actor.c
  src/libponyrt/gc/cycle.c
  src/libponyrt/gc/cycle.h
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
Labels: changelog - changed

#3516 Fix alpine build
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
  .cirrus.yml
Labels: DO NOT MERGE

#3515 Add OSSockOpt constants added by Linux 5.1 kernel
  packages/net/ossockopt.pony
  src/libponyrt/lang/socket.c
Labels: changelog - added

#3525 Add prebuilt FreeBSD 12.1 builds for releases
  .ci-scripts/x86-64-unknown-freebsd12.1-release.bash
  .cirrus.yml
  RELEASE_PROCESS.md
Labels: changelog - added

#3530 Let processmonitor chdir before exec
  packages/process/_process.pony
  packages/process/_test.pony
  packages/process/_test.sh
  packages/process/process_monitor.pony
  packages/stdlib/_test.pony
  src/libponyrt/lang/process.c
  src/libponyrt/lang/process.h
Labels: changelog - changed
