Repository ponylang/ponyc, pull requests merged in 2020-08, with the labels that each got.

#3609 Update to basing musl images off of Alpine 3.12
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
  .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
  .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
Labels: changelog - changed

#3619 Revert "Implement RFC0067"
  packages/logger/_test.pony
  packages/logger/logger.pony
Labels: changelog - changed

#3606 Always allow field access for objects defined inside a recover block
  src/libponyc/expr/reference.c
  test/libponyc/recover.cc
Labels: changelog - fixed

#3630 Fix build failure under GCC 10.2
  src/libponyc/expr/reference.c
Labels: changelog - fixed

#3629 Add prebuilt ponyc binaries for CentOS 8
  .ci-dockerfiles/x86-64-unknown-linux-centos8-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-centos8-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/3629.md
  BUILD.md
Labels: changelog - added
