Repository ponylang/ponyc, pull requests merged in 2021-07, with the labels that each got.

#3777 Fix bug where Flags.remove could set flags in addition to unsetting them
  .release-notes/3777.md
  packages/collections/_test.pony
  packages/collections/flag.pony
Labels: changelog - fixed

#3778 Allow Flags instances to be created with a set bit encoding
  .release-notes/3778.md
  packages/collections/_test.pony
  packages/collections/flag.pony
Labels: changelog - added

#3780 Don't allow PONYPATH to override standard library
  .release-notes/3779-fix.md
  src/libponyc/pkg/package.c
Labels: changelog - changed

#3783 Add support for prebuilt Rocky Linux versions
  .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/rocky.md
  BUILD.md
Labels: changelog - added

#3793 Fix OOM on MacOS when using xcode 12.5
  .release-notes/fix-3789.md
  src/libponyrt/mem/alloc.c
Labels: changelog - fixed

#3794 Change minimum supported MacOS API version to 10.14
  .release-notes/fix-3792.md
  src/libponyc/codegen/genexe.c
Labels: changelog - changed

#3798 Fix MacOS version mismatch warnings when linking Pony programs
  .release-notes/3789.md
  .release-notes/next-release.md
  CHANGELOG.md
  CMakeLists.txt
  src/libponyc/codegen/genexe.c
Labels: changelog - fixed

#3799 Fix the calculation of "is prime" for numbers after 1321.
  .release-notes/prime-fix.md
  packages/math/_test.pony
  packages/math/is_prime.pony
Labels: changelog - fixed

#3781 Prevent non-opaque structs from being used as behaviour parameters
  .release-notes/3765.md
  src/libponyc/verify/fun.c
  test/libponyc/codegen_trace.cc
  test/libponyc/verify.cc
Labels: changelog - fixed

#3808 Fixed Makefile for FreeBSD
  .release-notes/3808.md
  Makefile
Labels: changelog - fixed

#3809 Make FileMode._os public
  .release-notes/mode-os.md
  packages/files/_file_des.pony
  packages/files/directory.pony
  packages/files/file.pony
  packages/files/file_mode.pony
  packages/files/file_path.pony
Labels: changelog - changed

#3785 Package-level documentation (#3281)
  STYLE_GUIDE.md
  packages/bureaucracy/bureaucracy.pony
  packages/bureaucracy/custodian.pony
  packages/capsicum/capsicum.pony
  packages/collections/collections.pony
  packages/collections/persistent/persistent.pony
  packages/math/fibonacci.pony
  packages/math/math.pony
  packages/ponybench/ponybench.pony
  packages/ponytest/ponytest.pony
  packages/process/process.pony
  packages/process/process_monitor.pony
  packages/promises/promise.pony
  packages/promises/promises.pony
  packages/signals/sig.pony
  packages/signals/signals.pony
  packages/strings/strings.pony
  packages/term/term.pony
Labels: do not merge
