Repository ponylang/ponyc, pull requests merged in 2021-10, with the labels that each got.

#3871 Fix major source of runtime instability on non-x86 based platforms
  .release-notes/3871.md
  src/libponyrt/mem/pool.c
  src/libponyrt/sched/mpmcq.c
  src/libponyrt/sched/mpmcq.h
Labels: changelog - fixed

#3875 Fix segfaults with debug mode code on 64-bit Arm
  .release-notes/3875.md
  src/libponyc/codegen/host.cc
Labels: changelog - fixed

#3876 Add 64-bit Arm (Graviton) as a supported platform
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/3876.md
Labels: changelog - added

#3847 Reorder stdlib tests w/ suggested style
  STYLE_GUIDE.md
  packages/buffered/_test.pony
  packages/builtin_test/_test.pony
  packages/bureaucracy/_test.pony
  packages/cli/_test.pony
  packages/collections/_test.pony
  packages/collections/persistent/_test.pony
  packages/encode/base64/_test.pony
  packages/files/_test.pony
  packages/format/_test.pony
  packages/ini/_test.pony
  packages/itertools/_test.pony
  packages/json/_test.pony
  packages/logger/_test.pony
  packages/math/_test.pony
  packages/net/_test.pony
  packages/ponytest/ponytest.pony
  packages/process/_test.pony
  packages/promises/_test.pony
  packages/random/_test.pony
  packages/serialise/_test.pony
  packages/stdlib/_test.pony
  packages/strings/_test.pony
  packages/time/_test.pony
Labels: needs discussion

#3877 Turn arm and armhf CI tests back on
  .cirrus.yml
Labels: do not merge

#3879 Add build instructions for 32-bit Raspbian
  .release-notes/3879.md
  BUILD.md
Labels: changelog - added

#3895 Fix incorrect version in nightly ponyc builds
  .release-notes/3887.md
  Makefile
Labels: changelog - fixed
