Repository ponylang/ponyc, pull requests merged in 2021-04, with the labels that each got.

#3738 Add `IsPrime` checker to `math` package
  .release-notes/3738.md
  packages/math/_test.pony
  packages/math/is_prime.pony
  packages/stdlib/_test.pony
Labels: changelog - added

#3741 Use built-in offset argument to cpointer
  .release-notes/3741.md
  packages/process/_pipe.pony
Labels: changelog - fixed

#3743 Change supported FreeBSD to 13.0
  .ci-scripts/x86-64-unknown-freebsd-13.0-nightly.bash
  .ci-scripts/x86-64-unknown-freebsd-13.0-release.bash
  .cirrus.yml
  .release-notes/freebsd13.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - changed
