Repository ponylang/ponyc, pull requests merged in 2022-12, with the labels that each got.

#4269 Reduce stress test duration
  Makefile
  make.ps1
Labels: discuss during sync

#4271 Add dedicated stress test program
  .cirrus.yml
  Makefile
  make.ps1
  test/rt-stress/string-message-ubench/main.pony
Labels: discuss during sync

#4270 Remove macOS on Intel as a supported platform
  .cirrus.yml
  .github/workflows/cloudsmith-package-sychronised.yml
  .release-notes/bye-intel-macos.md
  INSTALL.md
  README.md
  RELEASE_PROCESS.md
Labels: changelog - changed, discuss during sync

#4256 Fix segfault caused by unsafe garbage collection optimization
  .release-notes/4526.md
  src/libponyc/ast/ast.c
  src/libponyc/ast/source.c
  src/libponyc/ast/stringtab.c
  src/libponyc/ast/symtab.c
  src/libponyc/ast/token.c
  src/libponyc/codegen/gendesc.c
  src/libponyc/pkg/package.c
  src/libponyc/pkg/program.c
  src/libponyc/reach/reach.c
  src/libponyc/type/reify.c
  src/libponyrt/ds/hash.h
  src/libponyrt/ds/list.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/gc/gc.c
  src/libponyrt/pony.h
  test/libponyc-run/regression-1118/main.pony
  test/libponyrt/ds/hash.cc
Labels: changelog - fixed

#4276 Fix incorrectly implemented PR #4243
  .release-notes/fix-4243.md
  src/libponyc/pass/docgen.c
Labels: changelog - fixed, discuss during sync

#4279 Allow building gbenchmark with newer Clang
  lib/CMakeLists.txt
Labels: discuss during sync

#4278 Fix an assert in `call.c` when checking an invalid argument for autorecover
  .release-notes/4278.md
  src/libponyc/expr/call.c
Labels: changelog - fixed

#4274 Fix an issue with infinite loops while typechecking some expressions
  .release-notes/4274.md
  src/libponyc/type/subtype.c
  test/libponyc-run/regression-3658/main.pony
  test/libponyc/type_check_subtype.cc
Labels: changelog - fixed, discuss during sync

#4283 Fix soundness bug introduced in Pony 0.51.2
  .release-notes/4283.md
  src/libponyc/expr/operator.c
  src/libponyc/type/cap.c
  src/libponyc/type/cap.h
  src/libponyc/type/safeto.c
  src/libponyc/type/safeto.h
  test/libponyc/CMakeLists.txt
  test/libponyc/cap_safety.cc
Labels: changelog - fixed, discuss during sync

#4288 Fix compiler crash introduced in #4283
  .release-notes/4287.md
  src/libponyc/type/safeto.c
  test/libponyc/cap_safety.cc
Labels: changelog - fixed, discuss during sync
