Repository ponylang/ponyc, pull requests merged in 2022-01, with the labels that each got.

#3955 Stop creating CentOS 8 prebuilt ponyc releases
  .ci-dockerfiles/x86-64-unknown-linux-centos8-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-centos8-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/centos-8-eol.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - changed

#3960 Hide C header implementation details related to actor pad size.
  .release-notes/hide_actor_pad_size.md
  src/libponyc/codegen/codegen.c
  src/libponyrt/actor/actor.h
  src/libponyrt/pony.h
Labels: changelog - changed

#3962 Change type of Env.root to AmbientAuth
  .release-notes/env-root-not-optional.md
  examples/echo/echo.pony
  examples/files/files.pony
  examples/mandelbrot/mandelbrot.pony
  examples/net/listener.pony
  examples/net/net.pony
  examples/net/pong.pony
  examples/under_pressure/main.pony
  minimal-cases/issue-629/629.pony
  packages/backpressure/backpressure.pony
  packages/builtin/env.pony
  packages/files/_test.pony
  packages/files/files.pony
  packages/ini/ini.pony
  packages/net/_test.pony
  packages/net/proxy.pony
  packages/net/tcp_connection.pony
  packages/net/tcp_listener.pony
  packages/net/udp_socket.pony
  packages/ponytest/ponytest.pony
  packages/process/_test.pony
  packages/process/process.pony
  packages/serialise/_test.pony
  test/libponyc-run/custom-serialisation/main.pony
  test/libponyc-run/runner/_find_executable.pony
  test/libponyc-run/runner/_tester.pony
  test/libponyc-run/runner/main.pony
  test/libponyc-run/string-serialisation/main.pony
Labels: changelog - changed

#3965 Remove simplebuiltin compiler option
  .release-notes/bye-simplebuiltin.md
  src/libponyc/options/options.c
  src/libponyc/pass/pass.h
  src/libponyc/pkg/package.c
Labels: changelog - changed

#3971 Fix return checking in behaviours and constructors
  .release-notes/3971.md
  src/libponyc/pass/syntax.c
  test/libponyc-run/lambda-with-return-in-behaviour/main.pony
  test/libponyc-run/lambda-with-return-in-constructor/main.pony
  test/libponyc-run/object-literal-with-return-in-behaviour/main.pony
  test/libponyc-run/object-literal-with-return-in-constructor/main.pony
Labels: changelog - fixed

#3975 Remove library mode option from ponyc
  .release-notes/3975.md
  src/libponyc/CMakeLists.txt
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/genlib.c
  src/libponyc/codegen/genlib.h
  src/libponyc/codegen/genopt.cc
  src/libponyc/codegen/host.cc
  src/libponyc/options/options.c
Labels: changelog - changed

#3973 Don't allow interfaces to have private methods
  .release-notes/3973.md
  CHANGELOG.md
  packages/builtin/asio_event.pony
  packages/builtin/stdin.pony
  packages/net/tcp_connection.pony
  packages/net/tcp_listener.pony
  packages/net/udp_socket.pony
  packages/process/process_monitor.pony
  packages/signals/signal_handler.pony
  packages/time/timers.pony
  src/libponyc/pass/verify.c
  src/libponyc/verify/type.c
  src/libponyc/verify/type.h
  test/libponyc/badpony.cc
Labels: changelog - changed

#3980 Fix compiler assertion failure when assigning error to a variable
  .release-notes/3823.md
  src/libponyc/expr/operator.c
  test/libponyc/badpony.cc
Labels: changelog - fixed

#3788 Add README for each examples/ entry
  examples/circle/README.md
  examples/commandline/README.md
  examples/counter/README.md
  examples/echo/README.md
  examples/fan-in/README.md
  examples/ffi-callbacks/README.md
  examples/ffi-callbacks/callbacks.pony
  examples/ffi-struct/README.md
  examples/files/README.md
  examples/gups_basic/README.md
  examples/gups_opt/README.md
  examples/helloworld/README.md
  examples/ifdef/README.md
  examples/lambda/README.md
  examples/mailbox/README.md
  examples/mandelbrot/README.md
  examples/mandelbrot/mandelbrot.pony
  examples/message-ubench/README.md
  examples/mixed/README.md
  examples/mixed/main.pony
  examples/n-body/README.md
  examples/net/README.md
  examples/overload/README.md
  examples/ponybench/README.md
  examples/ponybench/main.pony
  examples/printargs/README.md
  examples/producer-consumer/README.md
  examples/readline/README.md
  examples/ring/README.md
  examples/spreader/README.md
  examples/timers/README.md
  examples/under_pressure/README.md
  examples/yield/README.md
Labels: documentation
