Repository ponylang/ponyc, pull requests merged in 2022-03, with the labels that each got.

#4050 Add regression test for issue 2408.
  test/libponyc-run/regression-2408/main.pony
Labels: discuss during sync

#4018 Ban unstable variables
  .release-notes/3953.md
  src/libponyc/expr/array.c
  src/libponyc/expr/call.c
  src/libponyc/expr/control.c
  src/libponyc/expr/lambda.c
  src/libponyc/expr/operator.c
  src/libponyc/expr/reference.c
  src/libponyc/pass/flatten.c
  src/libponyc/pass/verify.c
  src/libponyc/type/alias.c
  src/libponyc/type/alias.h
  src/libponyc/type/cap.c
  src/libponyc/type/cap.h
  src/libponyc/type/reify.c
  src/libponyc/type/subtype.c
  src/libponyc/type/viewpoint.c
  src/libponyc/verify/fun.c
  test/libponyc/CMakeLists.txt
  test/libponyc/cap.cc
  test/libponyc/matchtype.cc
  test/libponyc/stable_type.cc
  test/libponyc/type_check_subtype.cc
Labels: changelog - fixed, discuss during sync

#4057 Fix crash with exhaustive match and generics
  .release-notes/3447.md
  src/libponyc/codegen/genmatch.c
  test/libponyc-run/regression-3447/main.pony
Labels: changelog - fixed, discuss during sync

#4058 Use a fixed Windows version for GitHub actions
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/pr.yml
Labels: discuss during sync

#4061 Fix parameter names not being checked
  .release-notes/4054.md
  src/libponyc/pass/sugar.c
  test/libponyc/sugar.cc
Labels: changelog - fixed, discuss during sync

#4066 Example heading in itertools package should be h4
  packages/itertools/iter.pony
Labels: discuss during sync

#4067 Fix compiler crash in HeapToStack optimization pass
  .release-notes/4059.md
  src/libponyc/codegen/genopt.cc
  test/libponyc-run/regression-4059/main.pony
Labels: changelog - fixed, discuss during sync

#4068 Remove infinite loop workaround
  src/libponyc/codegen/gentype.c
  src/libponyc/codegen/host.cc
Labels: discuss during sync

#4060 Allow to override the return type of FFI functions
  .release-notes/4060.md
  pony.g
  src/libponyc/ast/parser.c
  src/libponyc/ast/treecheckdef.h
  src/libponyc/codegen/gencall.c
  src/libponyc/expr/ffi.c
  src/libponyc/pass/sugar.c
  src/libponyc/pass/syntax.c
  src/libponyc/verify/call.c
  test/libponyc-run/ffi-different-returns/additional.c
  test/libponyc-run/ffi-different-returns/expected-exit-code.txt
  test/libponyc-run/ffi-different-returns/main.pony
  test/libponyc/badpony.cc
  test/libponyc/codegen_ffi.cc
  test/libponyc/ffi.cc
Labels: changelog - added, discuss during sync

#4065 Don't allow FFI calls in default methods or behaviors
  .release-notes/fix_3997.md
  packages/files/_test.pony
  src/libponyc/pass/syntax.c
  test/libponyc/badpony.cc
Labels: changelog - changed, discuss during sync

#4071 Add Asahi Linux build instructions
  BUILD.md
Labels: discuss during sync
