Repository ponylang/ponyc, pull requests merged in 2022-02, with the labels that each got.

#3978 Add "nodoc" annotation
  .release-notes/nodoc.md
  CHANGELOG.md
  packages/buffered/_test.pony
  packages/builtin_test/_test.pony
  packages/builtin_test/_test_valtrace.pony
  packages/bureaucracy/_test.pony
  packages/cli/_test.pony
  packages/collections/_test.pony
  packages/collections/persistent/_test.pony
  packages/encode/base64/_test.pony
  packages/files/_test.pony
  packages/format/_test.pony
  packages/ini/_test.pony
  packages/itertools/_test.pony
  packages/json/_test.pony
  packages/logger/_test.pony
  packages/math/_test.pony
  packages/net/_test.pony
  packages/process/_test.pony
  packages/promises/_test.pony
  packages/random/_test.pony
  packages/serialise/_test.pony
  packages/signals/_test.pony
  packages/stdlib/_test.pony
  packages/strings/_test.pony
  packages/time/_test.pony
  src/libponyc/pass/docgen.c
  src/libponyc/pass/syntax.c
Labels: changelog - added

#3984 Add a pony primitive that exposes scheduler information
  .release-notes/3984.md
  packages/runtime_info/auth.pony
  packages/runtime_info/runtime_info.pony
  packages/runtime_info/scheduler.pony
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
Labels: changelog - added, discuss during sync

#3990 Stop creating prebuilt ponyc releases for Ubuntu 21.04
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu21.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu21.04-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/issue-3982.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - changed, discuss during sync

#3989 Refactor how ponyint_cpu_core_pause is called
  src/libponyrt/sched/cpu.c
  src/libponyrt/sched/cpu.h
  src/libponyrt/sched/scheduler.c
Labels: discuss during sync

#3993 Fix runtime crash when tracing class iso containing struct val
  .release-notes/3993.md
  src/libponyrt/gc/actormap.c
  src/libponyrt/gc/actormap.h
  src/libponyrt/gc/gc.c
  src/libponyrt/gc/objectmap.c
  src/libponyrt/gc/objectmap.h
  test/libponyc-run/regression-3840/main.pony
Labels: changelog - fixed, discuss during sync

#3995 Revert "prevent non-opaque structs from being used as behaviour parameters"
  .release-notes/3995.md
  src/libponyc/verify/fun.c
  test/libponyc-run/regression-3765/main.pony
  test/libponyc/verify.cc
Labels: changelog - changed, discuss during sync

#3998 Fix package-level example in "files"
  packages/files/files.pony
Labels: discuss during sync

#3999 Fix bug in #3993
  src/libponyrt/gc/gc.c
Labels: discuss during sync

#4000 Remove out parameter from `pony_os_stdin_read`
  .release-notes/simplify_stdin_read.md
  packages/builtin/stdin.pony
  src/libponyrt/lang/stdfd.c
Labels: changelog - changed

#3988 Expose additional scheduler info via the runtime_info package
  .release-notes/3988.md
  packages/runtime_info/scheduler.pony
  src/libponyrt/sched/scheduler.c
Labels: changelog - added, discuss during sync

#3996 Change some pure compilation tests into runner tests
  test/libponyc-run/annotation-compound-expr/main.pony
  test/libponyc-run/annotation-methods/main.pony
  test/libponyc-run/annotation-standard-location-good/main.pony
  test/libponyc-run/annotation-types/main.pony
  test/libponyc-run/array-as-iso-consumed-elements/main.pony
  test/libponyc-run/array-as-iso/main.pony
  test/libponyc-run/array-as-val/main.pony
  test/libponyc-run/array-infer-from-apply-interface-box-element-in-tuple/main.pony
  test/libponyc-run/array-infer-from-apply-interface-val-element-no-arrow-this/main.pony
  test/libponyc-run/array-infer-from-apply-interface/main.pony
  test/libponyc-run/array-infer-from-array-iso/main.pony
  test/libponyc-run/array-infer-from-array-type/main.pony
  test/libponyc-run/array-infer-from-array-uso-with-as/main.pony
  test/libponyc-run/array-infer-from-array-val/main.pony
  test/libponyc-run/array-infer-from-interface-with-type-param/main.pony
  test/libponyc-run/array-infer-from-read-seq-and-read-element-interface/main.pony
  test/libponyc-run/array-infer-from-seq/main.pony
  test/libponyc-run/array-infer-from-values-call-with-iterator-antecedent/main.pony
  test/libponyc-run/array-infer-from-values-of-array-interface/main.pony
  test/libponyc-run/array-no-as-iso-consumed-elements/main.pony
  test/libponyc-run/array-no-as-iso/main.pony
  test/libponyc-run/array-no-as-val/main.pony
  test/libponyc/annotations.cc
  test/libponyc/array.cc
Labels: discuss during sync

#4003 Update `INSTALL.md` to mention ponyup for Windows.
  INSTALL.md
Labels: discuss during sync

#4004 Windows build script tweaks
  make.ps1
Labels: discuss during sync

#4007 Turn off running debug build Windows tests
  .cirrus.yml
Labels: discuss during sync

#4012 Add two while/else tests
  test/libponyc-run/while-else-trigger-else-clause/expected-exit-code.txt
  test/libponyc-run/while-else-trigger-else-clause/main.pony
  test/libponyc-run/while-else-trigger-while-body/expected-exit-code.txt
  test/libponyc-run/while-else-trigger-while-body/main.pony
Labels: discuss during sync

#3953 Ban variables whose capability is unsound to alias
  .release-notes/3953.md
  src/libponyc/expr/array.c
  src/libponyc/expr/call.c
  src/libponyc/expr/control.c
  src/libponyc/expr/lambda.c
  src/libponyc/expr/operator.c
  src/libponyc/expr/reference.c
  src/libponyc/pass/flatten.c
  src/libponyc/pass/verify.c
  src/libponyc/type/alias.c
  src/libponyc/type/cap.c
  src/libponyc/type/cap.h
  src/libponyc/type/viewpoint.c
  src/libponyc/verify/fun.c
  test/libponyc/CMakeLists.txt
  test/libponyc/cap.cc
  test/libponyc/stable_type.cc
Labels: changelog - fixed, discuss during sync

#3991 Add workaround for compiler assertion failure in Promise.flatten_next
  .release-notes/3991.md
  packages/promises/promise.pony
  test/libponyc-run/promise-flatten-next-regression-3856/main.pony
Labels: changelog - fixed, discuss during sync

#4006 Take exhaustive match into account when checking for field initialization
  .release-notes/issue-3616.md
  src/libponyc/CMakeLists.txt
  src/libponyc/pass/completeness.c
  src/libponyc/pass/completeness.h
  src/libponyc/pass/pass.c
  src/libponyc/pass/pass.h
  src/libponyc/pass/refer.c
  src/libponyc/verify/fun.c
  src/libponyc/verify/fun.h
  test/libponyc-run/regression-3615/main.pony
Labels: changelog - fixed, discuss during sync

#4005 Fix compiler crash related to using tuples as a generic constraint
  .release-notes/fix-3655.md
  src/libponyc/pass/flatten.c
  test/libponyc/flatten.cc
Labels: changelog - fixed, discuss during sync

#4019 Add corral to Windows docker images
  .dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
  .dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
Labels: discuss during sync

#4001 Add LeastCommonMultiple and GreatestCommonDivisor to math package
  .release-notes/lcm.md
  packages/math/_test.pony
  packages/math/greatest_common_divisor.pony
  packages/math/least_common_multiple.pony
Labels: changelog - added, discuss during sync

#4009 Fix incorrect "field not initialized" error with while/else
  .release-notes/while-else-initialize.md
  src/libponyc/pass/refer.c
  test/libponyc-run/while-else-can-initialize-fields/main.pony
  test/libponyc/refer.cc
Labels: changelog - fixed, discuss during sync

#4020 Fix fun merge time issue with overlapping PRs
  test/libponyc/refer.cc
  test/libponyc/verify.cc
Labels: discuss during sync

#4017 Fix compiler crash related to using tuples in a union as a generic constraint
  .release-notes/tuples-in-unions-constraint.md
  src/libponyc/pass/flatten.c
  test/libponyc/flatten.cc
Labels: changelog - fixed, discuss during sync

#4022 Fix incorrect code returned by ANSI.erase
  .release-notes/4022.md
  packages/term/ansi.pony
Labels: changelog - fixed, discuss during sync

#4024 Reimplement `with`
  .release-notes/4024.md
  pony.g
  src/libponyc/ast/ast.c
  src/libponyc/ast/ast.h
  src/libponyc/ast/frame.c
  src/libponyc/ast/lexer.c
  src/libponyc/ast/parser.c
  src/libponyc/ast/token.h
  src/libponyc/ast/treecheckdef.h
  src/libponyc/codegen/gencontrol.c
  src/libponyc/codegen/gencontrol.h
  src/libponyc/codegen/genexpr.c
  src/libponyc/expr/control.c
  src/libponyc/expr/control.h
  src/libponyc/expr/operator.c
  src/libponyc/pass/expr.c
  src/libponyc/pass/refer.c
  src/libponyc/pass/sugar.c
  src/libponyc/pass/verify.c
  src/libponyc/reach/reach.c
  src/libponyc/verify/control.c
  src/libponyc/verify/control.h
  test/libponyc-run/with-as-expression/expected-exit-code.txt
  test/libponyc-run/with-as-expression/main.pony
  test/libponyc-run/with-error-from-function/expected-exit-code.txt
  test/libponyc-run/with-error-from-function/main.pony
  test/libponyc-run/with-error-in-block/expected-exit-code.txt
  test/libponyc-run/with-error-in-block/main.pony
  test/libponyc-run/with-in-loop-with-break/expected-exit-code.txt
  test/libponyc-run/with-in-loop-with-break/main.pony
  test/libponyc-run/with-in-loop-with-continue/expected-exit-code.txt
  test/libponyc-run/with-in-loop-with-continue/main.pony
  test/libponyc-run/with-return/expected-exit-code.txt
  test/libponyc-run/with-return/main.pony
  test/libponyc-run/with-standard/expected-exit-code.txt
  test/libponyc-run/with-standard/main.pony
  test/libponyc/annotations.cc
  test/libponyc/sugar.cc
Labels: changelog - changed, discuss during sync

#4026 Fix the signature of Iter's map_stateful/map to not require ephemerals
  .release-notes/4026.md
  packages/itertools/iter.pony
Labels: changelog - fixed, discuss during sync

#4027 Use symbol table from definition scope when looking up references from default method bodies
  .release-notes/4027.md
  src/libponyc/ast/ast.c
  src/libponyc/ast/ast.h
  src/libponyc/pass/names.c
  src/libponyc/pass/refer.c
  test/libponyc-run/regression-2150/bar.pony
  test/libponyc-run/regression-2150/foo.pony
  test/libponyc-run/regression-2150/main.pony
  test/libponyc-run/regression-3737/lib/lib.pony
  test/libponyc-run/regression-3737/main.pony
Labels: changelog - fixed, discuss during sync

#4035 Remove `logger` package from the standard library
  .release-notes/remove-logger.md
  packages/logger/_test.pony
  packages/logger/logger.pony
  packages/stdlib/_test.pony
Labels: changelog - changed, discuss during sync

#4039 Fix LLVM IR verification error found via PonyCheck
  .release-notes/fix_llvm_call_receiver_type_cast.md
  src/libponyc/codegen/gencall.c
Labels: changelog - fixed, discuss during sync

#4041 Fix incorrect test names
  packages/cli/_test.pony
Labels: discuss during sync

#4034 Add PonyCheck to standard library
  .cirrus.yml
  .release-notes/add-ponycheck-to-stdlib.md
  examples/pony_check/.gitignore
  examples/pony_check/README.md
  examples/pony_check/async_tcp_property.pony
  examples/pony_check/collection_generators.pony
  examples/pony_check/custom_class.pony
  examples/pony_check/list_reverse.pony
  examples/pony_check/main.pony
  packages/pony_check/_test.pony
  packages/pony_check/ascii_range.pony
  packages/pony_check/for_all.pony
  packages/pony_check/generator.pony
  packages/pony_check/int_properties.pony
  packages/pony_check/pony_check.pony
  packages/pony_check/poperator.pony
  packages/pony_check/property.pony
  packages/pony_check/property_helper.pony
  packages/pony_check/property_runner.pony
  packages/pony_check/property_unit_test.pony
  packages/pony_check/randomness.pony
  packages/stdlib/_test.pony
Labels: changelog - added, discuss during sync

#4042 Remove unneeded `timeout` methods from ProcessMonitor tests
  packages/process/_test.pony
Labels: discuss during sync

#4043 Fix failed initialization bug in Process Monitor
  .release-notes/pm-init-error.md
  packages/process/_process.pony
  packages/process/process_monitor.pony
  packages/process/process_notify.pony
Labels: changelog - fixed, discuss during sync

#4031 Change the standard library pattern for object capabilities
  .release-notes/rfc-72.md
  examples/echo/echo.pony
  examples/files/files.pony
  examples/mandelbrot/mandelbrot.pony
  examples/net/listener.pony
  examples/net/net.pony
  examples/net/pong.pony
  examples/under_pressure/main.pony
  packages/backpressure/backpressure.pony
  packages/files/_test.pony
  packages/files/file_path.pony
  packages/files/files.pony
  packages/ini/ini.pony
  packages/net/_test.pony
  packages/net/dns.pony
  packages/net/net_address.pony
  packages/net/proxy.pony
  packages/net/tcp_connection.pony
  packages/net/tcp_listener.pony
  packages/net/udp_socket.pony
  packages/ponytest/ponytest.pony
  packages/process/_test.pony
  packages/process/process.pony
  packages/process/process_monitor.pony
  packages/runtime_info/auth.pony
  packages/runtime_info/scheduler.pony
  test/libponyc-run/runner/_find_executable.pony
  test/libponyc-run/runner/_test_definitions.pony
  test/libponyc-run/runner/_tester.pony
  test/libponyc-run/runner/main.pony
Labels: changelog - changed, discuss during sync

#4044 Update Windows version used as the base for Windows images
  .dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
  .dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
  .release-notes/windows-images.md
Labels: changelog - changed, discuss during sync

#4032 Rename `ponytest` package to conform to naming standards
  .release-notes/ponytest-rename.md
  examples/pony_check/async_tcp_property.pony
  examples/pony_check/list_reverse.pony
  examples/pony_check/main.pony
  packages/buffered/_test.pony
  packages/builtin_test/_test.pony
  packages/builtin_test/_test_valtrace.pony
  packages/bureaucracy/_test.pony
  packages/cli/_test.pony
  packages/collections/_test.pony
  packages/collections/persistent/_test.pony
  packages/encode/base64/_test.pony
  packages/files/_test.pony
  packages/format/_test.pony
  packages/ini/_test.pony
  packages/itertools/_test.pony
  packages/json/_test.pony
  packages/math/_test.pony
  packages/net/_test.pony
  packages/pony_check/_test.pony
  packages/pony_check/for_all.pony
  packages/pony_check/pony_check.pony
  packages/pony_check/property.pony
  packages/pony_check/property_helper.pony
  packages/pony_check/property_unit_test.pony
  packages/pony_test/_color.pony
  packages/pony_test/_group.pony
  packages/pony_test/_test_record.pony
  packages/pony_test/_test_runner.pony
  packages/pony_test/pony_test.pony
  packages/pony_test/test_helper.pony
  packages/pony_test/test_list.pony
  packages/pony_test/unit_test.pony
  packages/process/_test.pony
  packages/promises/_test.pony
  packages/random/_test.pony
  packages/serialise/_test.pony
  packages/signals/_test.pony
  packages/stdlib/_test.pony
  packages/strings/_test.pony
  packages/time/_test.pony
Labels: changelog - changed, discuss during sync
