Repository ponylang/ponyc, pull requests merged in 2022-04, with the labels that each got.

#4079 Revert "Fix issue that could lead to a muted actor being run (#3974)"
  src/libponyrt/actor/actor.c
Labels: discuss during sync

#4083 Strengthen the ordering for some atomic operations
  .release-notes/fix-4069.md
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/messageq.c
  src/libponyrt/asio/asio.c
  src/libponyrt/asio/epoll.c
  src/libponyrt/lang/directory.c
  src/libponyrt/mem/pagemap.c
  src/libponyrt/mem/pool.c
  src/libponyrt/sched/mpmcq.c
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/start.c
Labels: changelog - fixed, discuss during sync

#4082 Add to nightly stress tests
  .cirrus.yml
  Makefile
Labels: discuss during sync

#4087 Fix compiler assertion on FFI call
  src/libponyc/pass/syntax.c
  test/libponyc-run/ffi-call-in-initializer/additional.c
  test/libponyc-run/ffi-call-in-initializer/main.pony
Labels: discuss during sync

#4085 Add running our full pony program tests in debug mode
  Makefile
  make.ps1
  test/libponyc-run/runner/_coordinator.pony
Labels: discuss during sync

#4091 Corrected a few of the examples in the documentation.
  packages/backpressure/backpressure.pony
  packages/net/tcp_connection.pony
Labels: discuss during sync

#4092 Corrections to examples in documentaton for debug and net
  packages/debug/debug.pony
  packages/net/tcp_listener.pony
  packages/net/udp_socket.pony
Labels: discuss during sync

#4093 Corrections to examples in documentation:
  packages/collections/list_node.pony
  packages/pony_bench/pony_bench.pony
  packages/pony_check/property_unit_test.pony
  packages/process/process.pony
Labels: discuss during sync

#4094 Fix a runtime fault for Windows IOCP w/ memtrack messages.
  .release-notes/fix_windows_iocp_memtrack.md
  src/libponyrt/asio/event.c
Labels: changelog - fixed, discuss during sync

#4090 Add platform specific build documentation for FFI examples
  examples/ffi-callbacks/README.md
  examples/ffi-struct/README.md
Labels: discuss during sync

#4097 Add prebuilt ponyc releases for Ubuntu 22.04
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/4062.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4099 Run glibc Linux CI against Ubuntu 22.04
  .cirrus.yml
Labels: discuss during sync
