Repository ponylang/ponyc, pull requests merged in 2022-05, with the labels that each got.

#4106 Remove unneeded extra `box` in `fun box` definitions
  packages/buffered/reader.pony
  packages/builtin/array.pony
  packages/builtin/string.pony
  packages/cli/command.pony
  packages/cli/command_help.pony
  packages/cli/command_parser.pony
  packages/pony_bench/benchmark.pony
Labels: discuss during sync

#4104 Update aarch64 stress tests to run on Ubuntu 22.04
  .cirrus.yml
Labels: discuss during sync

#4101 Run Linux x86 stress tests against Ubuntu 22.04
  .cirrus.yml
Labels: discuss during sync

#4100 Update base image for glibc Linux docker images
  .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
  .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
  .github/workflows/cloudsmith-package-sychronised.yml
  .release-notes/4098.md
Labels: changelog - changed, discuss during sync

#4107 Fix initialization of an atomic variable in `ponyassert.c`.
  src/common/pony/detail/atomics.h
  src/libponyrt/platform/ponyassert.c
Labels: discuss during sync

#4108 Small fixes to CMake code for cross-compiling runtime bitcode.
  src/libponyrt/CMakeLists.txt
Labels: discuss during sync

#4110 Remove unneeded debug gating in find_kernel32
  src/libponyc/platform/vcvars.c
Labels: discuss during sync

#4109 Fix compilation error with PONY_NDEBUG
  src/libponyc/ast/ast.c
  src/libponyc/ast/token.c
Labels: discuss during sync

#4111 Add CI testing on M1 MacOS
  .cirrus.yml
Labels: discuss during sync

#4112 Don't use "mostly debug runtime" with release configurations
  .cirrus.yml
  .release-notes/4112.md
  src/libponyc/CMakeLists.txt
  src/libponyc/ast/ast.c
  src/libponyc/ast/token.c
  src/libponyc/codegen/gencall.c
  src/libponyc/codegen/genreference.c
  src/libponyc/expr/reference.c
  src/libponyc/pass/expr.c
  src/libponyc/pass/refer.c
  src/libponyc/pkg/program.c
  src/libponyrt/CMakeLists.txt
  test/libponyc/CMakeLists.txt
Labels: changelog - changed, discuss during sync

#4113 Add MacOS Apple Silicon nightly builds
  .ci-scripts/arm64-nightly.bash
  .cirrus.yml
Labels: discuss during sync

#4118 Make the full-program tests run in parallel
  Makefile
  make.ps1
Labels: discuss during sync

#4115 Add nightly stress testing on MacOS on Apple Silicon
  .cirrus.yml
Labels: discuss during sync

#4119 Add prebuilt ponyc releases on MacOS for Apple Silicon
  .ci-scripts/arm64-release.bash
  .cirrus.yml
  .release-notes/apple-silicon-mac-os-releases.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4120 Remove duplicate arch entry in x86 release script
  .ci-scripts/x86-64-release.bash
Labels: discuss during sync

#4121 Add debug build testing for Windows PRs
  .cirrus.yml
Labels: discuss during sync

#4122 Disable incorrect runtime assert for ASIO thread shutdown.
  .release-notes/fix_runtime_program_termination_assert.md
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/messageq.c
  src/libponyrt/actor/messageq.h
  src/libponyrt/asio/epoll.c
  src/libponyrt/asio/iocp.c
  src/libponyrt/asio/kqueue.c
  src/libponyrt/sched/scheduler.c
Labels: do not merge, changelog - fixed, discuss during sync

#4123 Update Array.from_cpointer documentation
  packages/builtin/array.pony
Labels: discuss during sync

#4117 Fix phrasing in the serialise package documentation
  packages/serialise/serialise.pony
Labels: discuss during sync
