Repository ponylang/ponyc, pull requests merged in 2022-08, with the labels that each got.

#4167 Fix for crash when methods with default private type params in remote packages are called
  .release-notes/4167.md
  src/libponyc/verify/call.c
  test/libponyc-run/private-type-as-default-argument-in-public-function/lib/lib.pony
  test/libponyc-run/private-type-as-default-argument-in-public-function/main.pony
Labels: changelog - fixed, discuss during sync

#4144 Enhance runtime stats tracking
  .release-notes/4144.md
  CMakeLists.txt
  Makefile
  examples/runtime_info/.gitignore
  examples/runtime_info/README.md
  examples/runtime_info/main.pony
  packages/builtin/platform.pony
  packages/builtin/runtime_options.pony
  packages/runtime_info/_actor_stats.pony
  packages/runtime_info/_scheduler_stats.pony
  packages/runtime_info/actor_stats.pony
  packages/runtime_info/auth.pony
  packages/runtime_info/scheduler.pony
  packages/runtime_info/scheduler_stats.pony
  src/libponyc/codegen/genprim.c
  src/libponyc/pkg/platformfuns.c
  src/libponyc/pkg/platformfuns.h
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/asio/asio.c
  src/libponyrt/asio/asio.h
  src/libponyrt/gc/actormap.c
  src/libponyrt/gc/actormap.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/gc/cycle.h
  src/libponyrt/gc/delta.c
  src/libponyrt/gc/delta.h
  src/libponyrt/gc/gc.c
  src/libponyrt/gc/gc.h
  src/libponyrt/gc/objectmap.c
  src/libponyrt/gc/objectmap.h
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/heap.h
  src/libponyrt/mem/pagemap.c
  src/libponyrt/mem/pagemap.h
  src/libponyrt/mem/pool.h
  src/libponyrt/options/options.h
  src/libponyrt/pony.h
  src/libponyrt/sched/mutemap.c
  src/libponyrt/sched/mutemap.h
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
  src/libponyrt/sched/start.c
  src/libponyrt/sched/systematic_testing.c
  src/libponyrt/sched/systematic_testing.h
  test/libponyrt/mem/heap.cc
Labels: do not merge, changelog - added, discuss during sync

#4170 Update windows ci image
  .ci-dockerfiles/x86-64-pc-windows-msvc-builder/Dockerfile
  .ci-dockerfiles/x86-64-pc-windows-msvc-builder/build-and-push.ps1
  .cirrus.yml
  make.ps1
Labels: discuss during sync

#4159 Fix incorrect atomics usage
  .release-notes/4159.md
  src/common/pony/detail/atomics.h
  src/libponyrt/mem/pool.c
  src/libponyrt/sched/mpmcq.c
Labels: discuss during sync

#4164 Run test suites and stress test in a debugger
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu22.04-builder/Dockerfile
  .ci-dockerfiles/cross-aarch64/Dockerfile
  .ci-dockerfiles/cross-arm/Dockerfile
  .ci-dockerfiles/cross-armhf/Dockerfile
  .ci-dockerfiles/cross-riscv64/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-gnu-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu18.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
  .cirrus.yml
  Makefile
  make.ps1
Labels: discuss during sync

#3278 Trigger GC for actors when they tell the cycle detector they're blocked
  src/libponyrt/actor/actor.c
Labels: discuss during sync

#4180 Fix bug in `StdStream.print`
  .release-notes/4180.md
  src/libponyrt/lang/stdfd.c
Labels: changelog - fixed, discuss during sync
