Repository ponylang/ponyc, pull requests merged in 2022-11, with the labels that each got.

#4225 Update build instructions
  BUILD.md
Labels: discuss during sync

#4227 Avoid fairly easy to trigger overflow in Windows Time.nanos code
  .release-notes/nanos-overflow.md
  packages/time/time.pony
Labels: changelog - fixed, discuss during sync

#4223 Fix incorrect interaction between String/Array reserve and Pointer realloc
  .release-notes/4223.md
  packages/builtin/array.pony
  packages/builtin/pointer.pony
  packages/builtin/string.pony
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/genprim.c
  src/libponyrt/actor/actor.c
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/heap.h
  src/libponyrt/pony.h
Labels: changelog - fixed, discuss during sync

#4229 Test building standard library documentation after each nightly release
  .ci-scripts/build-stdlib-documentation.bash
  .github/workflows/cloudsmith-package-sychronised.yml
Labels: discuss during sync

#4228 Sort package types in documentation
  .release-notes/4228.md
  src/libponyc/pass/docgen.c
Labels: changelog - changed, discuss during sync

#4226 Adapt docgen to use the mkdocs material theme
  .ci-dockerfiles/stdlib-builder/Dockerfile
  .release-notes/next-release.md
  CHANGELOG.md
  src/libponyc/logo.h
  src/libponyc/pass/docgen.c
  src/libponyc/pass/docgen.h
  src/libponyc/pkg/package.c
Labels: documentation, discuss during sync

#4236 Switch standard library documentation method
  .ci-scripts/build-and-push-stdlib-documentation.bash
  .github/workflows/cloudsmith-package-sychronised.yml
Labels: discuss during sync

#4239 Update docgen to generate source files that are ignored
  .release-notes/src-search-exclude.md
  src/libponyc/pass/docgen.c
Labels: changelog - added, discuss during sync

#4241 Install mkdocs-material-insiders in standard library builder image
  .ci-dockerfiles/stdlib-builder/Dockerfile
  .ci-dockerfiles/stdlib-builder/build-and-push.bash
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/generate-documentation.yml
  .github/workflows/rebuild-stdlib-builder.yml
Labels: discuss during sync

#4243 Don't include "home file" in documentation search
  .release-notes/docgen-search-home-file.md
  src/libponyc/pass/docgen.c
Labels: changelog - added, discuss during sync

#4246 Add support for erase left and erase line in term.ANSI
  .release-notes/rfc75.md
  packages/term/ansi.pony
Labels: changelog - added, discuss during sync

#4252 Improve TCP backpressure handling on Windows
  .release-notes/4081.md
  packages/net/tcp_connection.pony
  src/libponyrt/lang/socket.c
Labels: changelog - changed, discuss during sync

#4251 Fix multiple races within actor/cycle detector interactions
  .release-notes/cycle-races.md
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/gc/cycle.c
Labels: changelog - fixed, discuss during sync

#4185 Update supported FreeBSD to 13.1
  .ci-scripts/x86-64-unknown-freebsd-13.1-nightly.bash
  .ci-scripts/x86-64-unknown-freebsd-13.1-release.bash
  .cirrus.yml
  .release-notes/4185.md
  RELEASE_PROCESS.md
  benchmark/libponyrt/ds/hash.cc
  benchmark/libponyrt/mem/heap.cc
  lib/CMakeLists.txt
Labels: changelog - changed, discuss during sync

#4261 Update rocky8 and ubuntu18 builders
  .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu18.04-builder/Dockerfile
  .cirrus.yml
Labels: discuss during sync

#4262 Drop Rocky 8 support
  .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/rocky-drop.md
Labels: changelog - changed, discuss during sync

#4263 Fix crash when calling `(this.)create()`
  .release-notes/4263.md
  src/libponyc/expr/call.c
  test/libponyc-run/ctor-autorecover-this/main.pony
Labels: changelog - fixed, discuss during sync
