Repository ponylang/ponyc, pull requests merged in 2022-06, with the labels that each got.

#4131 Use hw.ncpu on macOS instead of nproc
  .cirrus.yml
  Makefile
Labels: discuss during sync

#4132 Fix String.f32 and String.f64 errors with non null terminated strings
  .release-notes/4132.md
  packages/builtin/string.pony
  packages/builtin_test/_test.pony
Labels: changelog - fixed, discuss during sync

#4133 Change `actor->muted` to no longer be atomic
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/sched/scheduler.c
Labels: discuss during sync

#4127 Fix for infinite Ranges
  .release-notes/4127.md
  packages/collections/_test.pony
  packages/collections/range.pony
Labels: changelog - fixed, discuss during sync

#4135 Remove `actor->is_muted` and replace with a flag
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
Labels: discuss during sync

#4141 Hide backpressure related functions in `actor` module
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
Labels: discuss during sync

#4143 Avoid clearing chunks at start of GC
  .release-notes/4143.md
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/heap.h
Labels: changelog - added, discuss during sync

#4145 Combine multiple `has_sync_flag` calls to minimize atomic operations
  src/libponyrt/actor/actor.c
Labels: discuss during sync

#4146 Remove `ponyint_heap_alloc*_final` functions
  benchmark/libponyrt/mem/heap.cc
  src/libponyrt/actor/actor.c
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/heap.h
  test/libponyrt/mem/heap.cc
Labels: discuss during sync

#4149 Ensure reachability of types returned by FFI calls
  .release-notes/4149.md
  src/libponyc/reach/reach.c
  test/libponyc-run/ffi-return-arg-reachable/additional.c
  test/libponyc-run/ffi-return-arg-reachable/expected-exit-code.txt
  test/libponyc-run/ffi-return-arg-reachable/main.pony
Labels: changelog - fixed, discuss during sync

#4152 Support void* (Pointer[None]) parameters in bare lambdas and functions
  .release-notes/4152.md
  src/libponyc/expr/call.c
  src/libponyc/expr/ffi.c
  src/libponyc/expr/ffi.h
  test/libponyc-run/bare-function-use-of-void-pointers/expected-exit-code.txt
  test/libponyc-run/bare-function-use-of-void-pointers/main.pony
  test/libponyc-run/bare-lambda-use-of-void-pointers/expected-exit-code.txt
  test/libponyc-run/bare-lambda-use-of-void-pointers/main.pony
  test/libponyc/bare.cc
Labels: changelog - fixed, discuss during sync
