Repository ponylang/ponyc, pull requests merged in 2023-04, with the labels that each got.

#4341 Fix bug in HeapToStack optimization pass
  .release-notes/4341.md
  src/libponyc/codegen/genopt.cc
  test/libponyc-run/regression-4340/main.pony
Labels: changelog - fixed, discuss during sync

#4328 Refactor `pony_type_t` for better struct packing.
  src/libponyc/ast/ast.c
  src/libponyc/ast/source.c
  src/libponyc/ast/stringtab.c
  src/libponyc/ast/symtab.c
  src/libponyc/ast/token.c
  src/libponyc/codegen/gendesc.c
  src/libponyc/pkg/package.c
  src/libponyc/pkg/program.c
  src/libponyc/reach/reach.c
  src/libponyc/type/reify.c
  src/libponyrt/ds/hash.h
  src/libponyrt/ds/list.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/pony.h
  test/libponyrt/ds/hash.cc
Labels: discuss during sync

#4349 Change supported MacOS version from Monterey to Ventura
  .cirrus.yml
  .release-notes/ventura.md
Labels: changelog - changed, discuss during sync

#4347 Fix a possible resource leak with `with` blocks
  .release-notes/4345.md
  src/libponyc/pass/sugar.c
Labels: changelog - changed, discuss during sync
