Repository ponylang/ponyc, pull requests merged in 2023-08, with the labels that each got.

#4370 Revert "Move heap ownership info from chunk to pagemap"
  packages/builtin_test/_test.pony
  src/libponyrt/gc/gc.c
  src/libponyrt/gc/objectmap.c
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/heap.h
  src/libponyrt/mem/pagemap.c
  src/libponyrt/mem/pagemap.h
  test/libponyrt/mem/heap.cc
  test/libponyrt/mem/pagemap.cc
Labels: discuss during sync

#4373 Move glibc x86 Linux CI from CirrusCI to GitHub
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
  .cirrus.yml
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
Labels: do not merge, discuss during sync

#4376 Add workflow to manually update the lib cache
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4378 Update version of github-actions-zulip
  .github/workflows/cirrus-failures.yml
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/nightlies.yml
  .github/workflows/stress-test-runtime.yml
Labels: discuss during sync

#4374 Update to actions/checkout v3
  .github/workflows/announce-a-release.yml
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/pr.yml
  .github/workflows/prepare-for-a-release.yml
  .github/workflows/rebuild-stdlib-builder.yml
Labels: discuss during sync

#4375 Improve string-message-unbench stress tester
  test/rt-stress/string-message-ubench/main.pony
Labels: discuss during sync

#4377 Move x86 Linux musl CI jobs from CirrusCI to Github Actions
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
  .cirrus.yml
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4384 Move arm CI jobs from CirrusCI to GitHub actions
  .ci-dockerfiles/cross-arm/Dockerfile
  .cirrus.yml
  .github/workflows/pr.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4385 Move armhf CI from CirrusCI to GitHub Actions
  .ci-dockerfiles/cross-armhf/Dockerfile
  .cirrus.yml
  .github/workflows/pr.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4388 Merge the "configure" and "build" pony build steps together
  .github/workflows/pr.yml
  .github/workflows/stress-test-runtime.yml
Labels: discuss during sync

#4387 Add includes necessary for Visual Studio 2022 v17.7.0
  src/libponyc/options/options.c
  src/libponyrt/lang/time.c
Labels: discuss during sync

#4393 Fix broken linking when using a sanitizer
  .release-notes/fix-sanitizer.md
  src/libponyc/codegen/genexe.c
Labels: changelog - fixed, discuss during sync

#4394 Add `make ponyc` for building just ponyc.
  Makefile
Labels: discuss during sync

#4392 Move aarch64 CI from native on Cirrus to QEMU on GitHub Actions
  .ci-dockerfiles/cross-aarch64/Dockerfile
  .cirrus.yml
  .github/workflows/pr.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
  Makefile
Labels: discuss during sync

#4372 Fix memory errors with some `--debug` program builds
  .release-notes/4369.md
  src/libponyc/codegen/genopt.cc
  test/libponyc-run/regression-4369/main.pony
Labels: changelog - fixed, discuss during sync

#4382 Drop FreeBSD as a supported platform
  .ci-scripts/x86-64-unknown-freebsd-13.1-nightly.bash
  .ci-scripts/x86-64-unknown-freebsd-13.1-release.bash
  .cirrus.yml
  .release-notes/bye-freebsd.md
  INSTALL.md
  README.md
  RELEASE_PROCESS.md
  SYSTEMATIC_TESTING.md
  examples/ffi-callbacks/README.md
  examples/ffi-struct/README.md
Labels: changelog - changed, discuss during sync

#4400 Make the concurrency group for PR workflow more scoped
  .github/workflows/pr.yml
Labels: discuss during sync

#4409 Add test runner support for spaces in debugger path name
  test/libponyc-run/runner/_find_executable.pony
  test/libponyc-run/runner/_tester.pony
Labels: discuss during sync

#4403 Drop macOS on Apple Silicon as a fully supported platform
  .cirrus.yml
  .release-notes/no-arm-macos.md
  INSTALL.md
  README.md
  RELEASE_PROCESS.md
Labels: changelog - changed, discuss during sync

#4408 Delete untagged stdlib builder images
  .github/workflows/cloudsmith-package-sychronised.yml
Labels: discuss during sync

#4406 Update documentation for Actor and Scheduler statistics
  packages/runtime_info/actor_stats.pony
  packages/runtime_info/scheduler_stats.pony
Labels: discuss during sync

#4411 Fix small output error in make.ps1
  make.ps1
Labels: discuss during sync

#4383 Move Windows CI from CirrusCI to GitHub Actions
  .ci-dockerfiles/x86-64-pc-windows-msvc-builder/Dockerfile
  .ci-dockerfiles/x86-64-pc-windows-msvc-builder/README.md
  .ci-dockerfiles/x86-64-pc-windows-msvc-builder/build-and-push.ps1
  .cirrus.yml
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
  make.ps1
Labels: discuss during sync

#4417 Fix failing CI tests that were run in LLDB 14 not reporting failures
  test/libponyc-run/runner/_tester.pony
Labels: do not merge, discuss during sync

#4416 Turn off the last of CirrusCI
  .cirrus.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/cirrus-failures.yml
  RELEASE_PROCESS.md
  make.ps1
Labels: discuss during sync

#4415 Add macOS Stress Tests
  .github/workflows/stress-test-runtime.yml
Labels: discuss during sync

#4407 Update supported Alpine version to 3.17 and later
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
  .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
  .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
  .release-notes/next-release.md
  BUILD.md
  CHANGELOG.md
  INSTALL.md
  src/libponyc/codegen/genexe.c
Labels: discuss during sync

#4418 Install LLDB 19 in Ubuntu 22 builder image
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
Labels: discuss during sync

#4405 Avoid hangs in async pony_check properties when using actions
  .release-notes/4405.md
  packages/pony_check/property_helper.pony
  packages/pony_check/property_runner.pony
Labels: changelog - fixed, discuss during sync

#4414 Add support for building libponyc-standalone.a on FreeBSD
  src/libponyc/CMakeLists.txt
  test/libponyc-run/ffi-libponyc-standalone/main.pony
Labels: discuss during sync

#4419 Use changelog-bot-action from GitHub Container Registry
  .github/workflows/changelog-bot.yml
Labels: discuss during sync

#4421 Use release-bot-action from GitHub Container Registry
  .github/workflows/announce-a-release.yml
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/prepare-for-a-release.yml
  .github/workflows/release.yml
Labels: discuss during sync

#4422 Update to release-notes-bot-action 0.3.7
  .github/workflows/release-notes.yml
Labels: discuss during sync

#4423 Update to release-notes-reminder-bot-action 0.1.1
  .github/workflows/release-notes-reminder.yml
Labels: discuss during sync

#4425 Move private CI images from DockerHub to GitHub Container Registry
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/build-and-push.bash
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu22.04-builder/Dockerfile
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu22.04-builder/build-and-push.bash
  .ci-dockerfiles/cross-aarch64/Dockerfile
  .ci-dockerfiles/cross-aarch64/build-and-push.bash
  .ci-dockerfiles/cross-arm/Dockerfile
  .ci-dockerfiles/cross-arm/build-and-push.bash
  .ci-dockerfiles/cross-armhf/Dockerfile
  .ci-dockerfiles/cross-armhf/build-and-push.bash
  .ci-dockerfiles/cross-riscv64/Dockerfile
  .ci-dockerfiles/cross-riscv64/build-and-push.bash
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/build-and-push.bash
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/build-and-push.bash
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4426 Update repository dispatch action to v2.1.1
  .github/workflows/cloudsmith-package-sychronised.yml
Labels: discuss during sync
