Repository ponylang/ponyc, pull requests merged in 2023-10, with the labels that each got.

#4455 Fix compilation error when building with pool_memalign in release mode
  .github/workflows/pr.yml
  .release-notes/fix-4431.md
  src/libponyrt/mem/pool_memalign.c
Labels: changelog - fixed, discuss during sync

#4458 Fix compiler bug that allows an unsafe data access pattern
  .release-notes/issue-4244.md
  src/libponyc/type/alias.c
  test/libponyc/recover.cc
Labels: changelog - fixed, discuss during sync

#4460 Note breaking change nature of compiler bug fix
  .release-notes/next-release.md
  CHANGELOG.md
Labels: discuss during sync

#4461 Update INSTALL_DOCKER for GitHub Container Registry change
  INSTALL_DOCKER.md
Labels: discuss during sync

#4456 Run musl CI tests using LLDB
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4466 Fix compiling Pony programs on X86 MacOS when XCode 15 is the linker
  .release-notes/ldclassic.md
  src/libponyc/CMakeLists.txt
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/genexe.c
  src/libponyrt/CMakeLists.txt
Labels: changelog - fixed, discuss during sync

#4467 Disallow `return` at the end of a `with` block
  .release-notes/4464.md
  src/libponyc/expr/control.c
  test/full-program-tests/with-return/expected-exit-code.txt
  test/full-program-tests/with-return/main.pony
  test/libponyc/CMakeLists.txt
  test/libponyc/with.cc
Labels: changelog - changed, discuss during sync

#4471 Set MacOS platform version in one place
  CMakeLists.txt
  src/libponyc/CMakeLists.txt
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/genexe.c
  src/libponyrt/CMakeLists.txt
Labels: discuss during sync
