Repository ponylang/ponyc, pull requests merged in 2023-01, with the labels that each got.

#4280 Implement empty ranges RFC
  .release-notes/4280.md
  packages/collections/_test.pony
  packages/collections/range.pony
Labels: do not merge, changelog - changed, discuss during sync

#4286 Remove DECnet header
  src/libponyrt/lang/socket.c
Labels: discuss during sync

#4293 Fix infinite loop in compiler
  .release-notes/4291-hang.md
  src/libponyc/codegen/gencall.c
Labels: changelog - fixed, discuss during sync

#4292 Fix compiler segfault caused by infinite recursion
  .release-notes/4291-segfault.md
  src/libponyc/codegen/gencall.c
Labels: changelog - fixed, discuss during sync

#4294 Fix runtime segfault
  .release-notes/fix-4284.md
  src/libponyrt/gc/gc.c
  test/libponyc-run/regression-4284/main.pony
Labels: changelog - fixed, discuss during sync

#4305 Remove unneeded Max-FutureTime from Dockerfiles
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/Dockerfile
Labels: discuss during sync

#4304 Fix LLVM configuration override
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/cross-aarch64/Dockerfile
  .ci-dockerfiles/cross-arm/Dockerfile
  .ci-dockerfiles/cross-armhf/Dockerfile
  .ci-dockerfiles/cross-riscv64/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-gnu-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu18.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .cirrus.yml
  BUILD.md
  CMakeLists.txt
  benchmark/libponyc/CMakeLists.txt
  benchmark/libponyrt/CMakeLists.txt
  lib/CMakeLists.txt
  src/libponyc/CMakeLists.txt
  src/libponyrt/CMakeLists.txt
  src/ponyc/CMakeLists.txt
  test/libponyc/CMakeLists.txt
  test/libponyrt/CMakeLists.txt
Labels: discuss during sync

#4303 Create libponyc-standalone on MacOS
  .release-notes/4303.md
  src/libponyc/CMakeLists.txt
Labels: changelog - added, discuss during sync

#4299 Remove ambiguity from "not safe to write" compiler error message
  .release-notes/4299.md
  src/libponyc/expr/operator.c
  test/libponyc/badpony.cc
Labels: changelog - fixed, discuss during sync

#4310 Always include llvm_args in the pass_opt_t struct
  src/libponyc/pass/pass.h
Labels: discuss during sync

#4311 Display full platform value in Linux install instructions
  INSTALL.md
Labels: discuss during sync

#4313 Remove explicit --platform from end user ponyc Dockerfiles
  .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
  .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
  .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
  .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
Labels: discuss during sync

#4312 Stop building the "x86-64-unknown-linux-gnu" ponyc package
  .ci-dockerfiles/cross-aarch64/Dockerfile
  .ci-dockerfiles/cross-arm/Dockerfile
  .ci-dockerfiles/cross-armhf/Dockerfile
  .ci-dockerfiles/cross-riscv64/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-gnu-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-gnu-builder/build-and-push.bash
  .cirrus.yml
  .release-notes/no-more-gnu.md
Labels: changelog - changed, discuss during sync

#4316 Don't include libxml2 when building llvm libs.
  lib/CMakeLists.txt
Labels: discuss during sync

#4307 Build ponyc-standalone.lib for windows
  .release-notes/4307.md
  src/libponyc/CMakeLists.txt
  src/libponyc/ast/ast.h
  src/libponyc/ast/token.h
Labels: changelog - added, discuss during sync

#4317 Add missing file to runner cmake
  test/libponyc-run/runner/CMakeLists.txt
Labels: discuss during sync
