Repository ponylang/ponyc, pull requests merged in 2024-10, with the labels that each got.

#4522 Fix use after free bug in actor heap finalisation that can lead to a segfault
  .release-notes/4522.md
  src/libponyrt/mem/heap.c
  test/full-program-tests/large-dependent-finalisers/additional.cc
  test/full-program-tests/large-dependent-finalisers/expected-exit-code.txt
  test/full-program-tests/large-dependent-finalisers/main.pony
  test/full-program-tests/small-dependent-finalisers/additional.cc
  test/full-program-tests/small-dependent-finalisers/expected-exit-code.txt
  test/full-program-tests/small-dependent-finalisers/main.pony
Labels: triggers release, changelog - fixed, discuss during sync

#4527 Make heap small chunk size setting logic more precise/correct
  .release-notes/4527.md
  src/libponyrt/mem/heap.c
Labels: changelog - fixed, discuss during sync

#4525 Update to actions/cache version 4
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4528 Make actor pad automagically calculated
  src/libponyrt/actor/actor.h
Labels: discuss during sync

#4530 Add CI test that everything works when runtimestats are on
  .github/workflows/pr.yml
Labels: discuss during sync

#4531 Recycle actor heap chunks after GC instead of returning to pool
  .release-notes/4531.md
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/heap.h
  src/libponyrt/mem/heap_chunk_sorting.h
Labels: changelog - changed, discuss during sync

#4534 Disable actor heap large chunk recycling
  src/libponyrt/mem/heap.c
Labels: discuss during sync

#4535 Fix heap chunk recycling memory leak and another bug
  src/libponyrt/mem/heap.c
Labels: discuss during sync
