Repository ponylang/ponyc, pull requests merged in 2024-12, with the labels that each got.

#4560 Add py3-lldb to musl ci builder
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
Labels: discuss during sync

#4559 Don't use lldb for macos because stdlib tests fail silently with it
  .github/workflows/pr.yml
Labels: discuss during sync

#4563 Fix incorrect LLVM CI caching
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4557 Add Fedora 41 as a supported platform
  .ci-dockerfiles/x64-64-unknown-linux-fedora41-builder/Dockerfile
  .ci-dockerfiles/x64-64-unknown-linux-fedora41-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/release.yml
  .release-notes/fedora41.md
  BUILD.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4558 Drop Fedora 39 support
  .ci-dockerfiles/x64-64-unknown-linux-fedora39-builder/Dockerfile
  .ci-dockerfiles/x64-64-unknown-linux-fedora39-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/release.yml
  .release-notes/fedora39.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - changed, discuss during sync

#4562 Update Pony musl Docker images to Alpine 3.20
  .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
  .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
  .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
  .release-notes/alpine-320.md
  lib/CMakeLists.txt
  lib/llvm/patches/llvm15-musl-lseek64.diff
  packages/files/file.pony
  src/libponyrt/lang/io.c
Labels: discuss during sync

#4556 Fix rare termination logic failures that could result in early shutdown
  .release-notes/4556.md
  Makefile
  src/libponyrt/asio/epoll.c
  src/libponyrt/asio/event.c
  src/libponyrt/asio/iocp.c
  src/libponyrt/asio/kqueue.c
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
Labels: changelog - fixed, discuss during sync

#4547 Add support for pinning actors to a dedicated scheduler thread
  .release-notes/4547.md
  packages/actor_pinning/actor_pinning.pony
  packages/actor_pinning/auth.pony
  packages/builtin/runtime_options.pony
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/options/options.h
  src/libponyrt/sched/cpu.c
  src/libponyrt/sched/cpu.h
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
  src/libponyrt/sched/start.c
  src/libponyrt/sched/systematic_testing.c
  src/libponyrt/sched/systematic_testing.h
  test/full-program-tests/pinned-actor/expected-exit-code.txt
  test/full-program-tests/pinned-actor/main.pony
Labels: changelog - added, discuss during sync
