Repository ponylang/ponyc, pull requests merged in 2024-02, with the labels that each got.

#4489 Update to actions/checkout@v4.1.1
  .github/workflows/announce-a-release.yml
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/generate-documentation.yml
  .github/workflows/lint-action-workflows.yml
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/prepare-for-a-release.yml
  .github/workflows/rebuild-stdlib-builder.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4491 Fix compiler warning
  src/libponyc/codegen/genopt.cc
Labels: discuss during sync

#4490 Fix for potential memory corruption in `Array.copy_to`
  .release-notes/4174.md
  packages/builtin/array.pony
  packages/builtin_test/_test.pony
  test/full-program-tests/regression-4174/expected-exit-code.txt
  test/full-program-tests/regression-4174/main.pony
Labels: changelog - fixed, discuss during sync

#4486 Fix bug when serializing bare lambdas
  .release-notes/4479.md
  src/libponyc/codegen/genserialise.c
  test/full-program-tests/regression-4479/main.pony
Labels: changelog - fixed, discuss during sync

#4493 Add constrained_types package to the standard library
  .release-notes/4493.md
  examples/constrained_type/.gitignore
  examples/constrained_type/README.md
  examples/constrained_type/main.pony
  packages/constrained_types/_test.pony
  packages/constrained_types/constrained.pony
  packages/constrained_types/constrained_types.pony
  packages/stdlib/_test.pony
Labels: changelog - added, discuss during sync

#4495 Update Zulip send message action
  .github/workflows/changelog-bot.yml
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/nightlies.yml
  .github/workflows/release-notes.yml
  .github/workflows/stress-test-runtime.yml
Labels: discuss during sync

#4498 Update actionlint
  .github/workflows/lint-action-workflows.yml
Labels: discuss during sync

#4499 Adding a missing backtick in the documentation.
  packages/constrained_types/constrained_types.pony
Labels: discuss during sync
