Repository ponylang/ponyc, pull requests merged in 2024-01, with the labels that each got.

#4476 Fix missing "runtime_info" package documentation
  .release-notes/4476.md
  packages/runtime_info/_test.pony
  packages/stdlib/_test.pony
Labels: changelog - fixed, discuss during sync

#4478 EDITORS.md: add Kakoune text editor
  EDITORS.md
Labels: discuss during sync

#4481 Use the correct LLVM intrinsics for `powi` on *nix.
  .release-notes/4481.md
  packages/builtin/float.pony
  test/full-program-tests/regression-4480/main.pony
Labels: changelog - fixed, discuss during sync

#4483 Add Fedora 39 builder
  .ci-dockerfiles/x64-64-unknown-linux-fedora39-buiilder/Dockerfile
  .ci-dockerfiles/x64-64-unknown-linux-fedora39-buiilder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/release.yml
Labels: discuss during sync

#4484 Slim down the Fedora 39 builder some
  .ci-dockerfiles/x64-64-unknown-linux-fedora39-builder/Dockerfile
  .ci-dockerfiles/x64-64-unknown-linux-fedora39-builder/build-and-push.bash
Labels: discuss during sync

#4485 Add Fedora 39 as a supported platform
  .release-notes/fedora-39.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4487 Add MacOS on Apple Silicon as a supported platform
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .release-notes/welcome-back-m1.md
  INSTALL.md
  README.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4488 Send event to corral and ponyup on arm64 macos nightlies being released
  .github/workflows/cloudsmith-package-sychronised.yml
Labels: discuss during sync
