Repository ponylang/ponyc, pull requests merged in 2024-04, with the labels that each got.

#4505 Fix compiler crash
  .release-notes/4505.md
  src/libponyc/pass/refer.c
  test/libponyc/refer.cc
Labels: changelog - fixed, discuss during sync

#4508 Add prebuilt ponyc binaries for Ubuntu 24.04
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu24.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu24.04-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
  .release-notes/ubuntu24.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4509 Update cross-aarch64 builder to Ubuntu 24.04
  .ci-dockerfiles/cross-aarch64/Dockerfile
  .github/workflows/pr.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4510 Update cross-arm builder to Ubuntu 24.04
  .ci-dockerfiles/cross-arm/Dockerfile
  .github/workflows/pr.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4511 Update the cross-armhf builder to Ubuntu 24.04
  .ci-dockerfiles/cross-armhf/Dockerfile
  .github/workflows/pr.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4512 Update cross-riscv64 builder to Ubuntu 24.04
  .ci-dockerfiles/cross-riscv64/Dockerfile
  .github/workflows/pr.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync
