Repository ponylang/ponyc, pull requests merged in 2025-01, with the labels that each got.

#4575 Change stack_depth_t to size_t on OpenBSD
  .release-notes/4575.md
  src/libponyrt/platform/ponyassert.c
Labels: changelog - changed, discuss during sync

#4578 Fix possible null dereference
  src/libponyc/type/compattype.c
Labels: discuss during sync

#4577 Update google benchmark dependency
  lib/CMakeLists.txt
Labels: discuss during sync

#4583 Make sure scheduler threads don't ACK the quiescence protocol CNF messages if they have an actor waiting to be run
  .release-notes/4583.md
  src/libponyrt/sched/scheduler.c
  test/full-program-tests/regression-4582/expected-exit-code.txt
  test/full-program-tests/regression-4582/main.pony
Labels: changelog - fixed, discuss during sync

#4567 Deterministic serialisation for cross binary communication
  packages/serialise/serialise.pony
  src/libponyc/ast/ast.c
  src/libponyc/ast/source.c
  src/libponyc/ast/stringtab.c
  src/libponyc/ast/symtab.c
  src/libponyc/ast/token.c
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/codegen.h
  src/libponyc/codegen/gendesc.c
  src/libponyc/codegen/gendesc.h
  src/libponyc/codegen/genexe.c
  src/libponyc/codegen/genname.c
  src/libponyc/codegen/genname.h
  src/libponyc/codegen/genprim.c
  src/libponyc/codegen/genserialise.c
  src/libponyc/codegen/genserialise.h
  src/libponyc/codegen/gentype.c
  src/libponyc/pass/pass.h
  src/libponyc/pkg/package.c
  src/libponyc/pkg/program.c
  src/libponyc/reach/reach.c
  src/libponyc/reach/reach.h
  src/libponyc/type/reify.c
  src/libponyrt/ds/fun.c
  src/libponyrt/ds/fun.h
  src/libponyrt/ds/hash.h
  src/libponyrt/ds/list.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/gc/serialise.c
  src/libponyrt/gc/serialise.h
  src/libponyrt/pony.h
  src/libponyrt/sched/start.c
  test/libponyrt/ds/hash.cc
Labels: discuss during sync

#4568 Unionize actor heap large and small chunks
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/heap.h
  src/libponyrt/mem/heap_chunk_sorting.h
  test/libponyrt/mem/heap.cc
Labels: discuss during sync

#4586 Update ubuntu 24 builder
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu24.04-builder/Dockerfile
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4590 Limit some workflow permissions
  .github/workflows/add-discuss-during-sync.yml
  .github/workflows/changelog-bot.yml
  .github/workflows/lint-action-workflows.yml
  .github/workflows/pr.yml
  .github/workflows/release-notes-reminder.yml
  .github/workflows/release-notes.yml
Labels: discuss during sync

#4591 Limit permissions when stress tests are run
  .github/workflows/stress-test-runtime.yml
Labels: discuss during sync

#4589 Move aarch64 from QEMU to native aarch64 machines
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu24.04-builder/Dockerfile
  .ci-dockerfiles/aarch64-unknown-linux-ubuntu24.04-builder/build-and-push.bash
  .ci-dockerfiles/cross-aarch64/Dockerfile
  .ci-dockerfiles/cross-aarch64/build-and-push.bash
  .github/workflows/lint-action-workflows.yml
  .github/workflows/pr.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4593 Apply default options for a CLI parent command when a sub command is parsed
  .release-notes/4593.md
  packages/cli/_test.pony
  packages/cli/command_parser.pony
Labels: changelog - fixed, discuss during sync

#4592 Upgrade googletest dependency
  lib/CMakeLists.txt
Labels: discuss during sync

#4584 Manual poisoning for pool/heap when using address sanitizer
  .github/workflows/pr.yml
  CMakeLists.txt
  src/libponyc/codegen/genfun.c
  src/libponyrt/gc/cycle.c
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/pool.c
  src/libponyrt/mem/pool.h
  test/libponyrt/mem/pool.cc
Labels: discuss during sync

#4595 Fix compiler crash from `match` with extra parens around `let` in tuple
  .release-notes/4595.md
  src/libponyc/codegen/genmatch.c
  test/full-program-tests/regression-4412/expected-exit-code.txt
  test/full-program-tests/regression-4412/main.pony
Labels: changelog - fixed, discuss during sync

#4596 Reorganize CI sanitizers pull request job
  .github/workflows/pr.yml
Labels: discuss during sync

#4588 Fix soundness problem when matching `iso` variables
  .release-notes/4588.md
  src/libponyc/codegen/genmatch.c
  src/libponyc/expr/match.c
  src/libponyc/type/matchtype.c
  src/libponyc/type/matchtype.h
  src/libponyc/type/subtype.c
  test/libponyc/badpony.cc
  test/libponyc/matchtype.cc
Labels: changelog - fixed, discuss during sync
