Repository ponylang/ponyc, pull requests merged in 2025-02, with the labels that each got.

#4598 ubsan: fix "call to function through pointer to incorrect function type"
  src/libponyc/codegen/genprim.c
  src/libponyrt/ds/hash.h
  src/libponyrt/ds/list.h
Labels: discuss during sync

#4599 ubsan: fix buildflagset "applying non-zero offset to null pointer"
  src/libponyc/pkg/buildflagset.c
Labels: discuss during sync

#4602 Fix null pointer argument
  src/libponyc/reach/reach.c
Labels: discuss during sync

#4601 Fix member access within null pointer of type 'pass_opt_t'
  src/libponyc/type/lookup.c
Labels: discuss during sync

#4605 Make cycle detector test less likely to time out
  test/full-program-tests/cycle-detector/main.pony
Labels: discuss during sync

#4607 Make cycle detector test less likely to time out again
  src/libponyrt/sched/scheduler.c
  test/full-program-tests/cycle-detector/main.pony
Labels: discuss during sync

#4600 Fix leak of type from deferred_reify in gen_tuple
  src/libponyc/codegen/genreference.c
Labels: discuss during sync

#4603 Fix unaligned read in fun.c siphash
  src/libponyrt/ds/fun.c
Labels: discuss during sync

#4606 Resurrect pony_always_assert and decouple it from pony_ndebug
  src/common/ponyassert.h
  src/libponyc/CMakeLists.txt
  src/libponyc/ast/ast.c
  src/libponyc/ast/token.c
  test/libponyc/CMakeLists.txt
Labels: discuss during sync

#4617 Don't run GC for zombie actors when they are blocked
  src/libponyrt/actor/actor.c
Labels: discuss during sync

#4616 Fix use-after-free triggered by fast actor reaping when the cycle detector is active
  .release-notes/4616.md
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/gc/cycle.c
Labels: changelog - fixed, discuss during sync

#4618 Remove invalid asserts from ASIO system
  src/libponyrt/asio/epoll.c
  src/libponyrt/asio/iocp.c
  src/libponyrt/asio/kqueue.c
Labels: discuss during sync

#4615 Remove code related to ACTORMSG_DESTROYED and ctx for ponyint_destroy
  examples/dtrace/mbox-size-all-actor-messages.d
  examples/dtrace/telemetry.d
  examples/systemtap/telemetry.stp
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/genexe.c
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/gc/cycle.h
Labels: discuss during sync

#4611 Add aarch64 Linux stress tests with the cycle detector enabled
  .github/workflows/stress-test-runtime.yml
Labels: discuss during sync

#4620 Fix incorrect printing of runtime stats
  .release-notes/4620.md
  src/libponyrt/actor/actor.c
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
Labels: changelog - fixed, discuss during sync

#4621 Fix memory leak
  .release-notes/leak.md
  src/libponyrt/sched/mpmcq.c
  src/libponyrt/sched/mpmcq.h
  src/libponyrt/sched/scheduler.c
Labels: changelog - fixed, discuss during sync

#4623 Fix warning from grep when running make
  Makefile
Labels: discuss during sync

#4625 Fix being unable to compile programs that use runtime info on Windows
  .release-notes/a.md
  packages/runtime_info/_test.pony
  src/libponyrt/actor/actor.c
  src/libponyrt/sched/scheduler.c
Labels: changelog - fixed, discuss during sync

#4630 Add new runtime stress test
  .github/workflows/stress-test-runtime.yml
  Makefile
  make.ps1
  test/rt-stress/tcp-open-close/README.md
  test/rt-stress/tcp-open-close/tcp-open-close.pony
Labels: discuss during sync

#4631 Update the QEMU used in our cross runner
  .ci-dockerfiles/cross-arm/Dockerfile
  .ci-dockerfiles/cross-armhf/Dockerfile
  .github/workflows/pr.yml
Labels: discuss during sync

#4627 Rename the --ponyc option to the full-program-runner
  Makefile
  make.ps1
  test/full-program-runner/_cli_options.pony
  test/full-program-runner/_tester.pony
Labels: discuss during sync

#4633 Configure MacOS networking before running network related stress tests
  .ci-scripts/macOS-configure-networking.bash
  .github/workflows/stress-test-runtime.yml
Labels: discuss during sync

#4634 Add macos 14 stress tests
  .github/workflows/stress-test-runtime.yml
Labels: do not merge, discuss during sync

#4637 Update Windows CI to Windows 2025
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-runtime.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4635 Add workflow to test with "very up-to-date" tools
  .ci-dockerfiles/x86-64-unknown-linux-arch-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-arch-builder/build-and-push.bash
  .github/workflows/test-with-latest-tools.yml
Labels: discuss during sync

#4636 Build examples as part of Windows CI
  .github/workflows/pr.yml
  make.ps1
Labels: discuss during sync

#4628 Don't duplicate match checks for inherited trait bodies
  .release-notes/4628.md
  src/libponyc/expr/match.c
  test/full-program-tests/regression-4612/main.pony
Labels: changelog - fixed, discuss during sync

#4632 Don't duplicate visibility tests for inherited trait bodies
  .release-notes/fix-4613.md
  src/libponyc/type/lookup.c
  test/full-program-tests/regression-4613/main.pony
  test/full-program-tests/regression-4613/pkg/trait.pony
Labels: changelog - fixed, discuss during sync

#4638 Address edge case in ponyint_formattime
  src/libponyrt/lang/time.c
Labels: do not merge, discuss during sync

#4640 Really fix #4613
  CHANGELOG.md
  src/libponyc/type/lookup.c
  test/full-program-tests/regression-4613/main.pony
  test/full-program-tests/regression-4613/pkg/trait.pony
  test/full-program-tests/regression-4613/regression-4613
Labels: discuss during sync
