Repository ponylang/ponyc, pull requests merged in 2025-03, with the labels that each got.

#4643 Properly unset FLAG_BLOCKED when sending an unblock message
  src/libponyrt/actor/actor.c
Labels: discuss during sync

#4644 Add live asio event tracking for debugging
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/asio/event.c
  src/libponyrt/gc/cycle.c
Labels: discuss during sync

#4646 Fix ASIO thread scheduler index
  src/libponyrt/asio/asio.h
  src/libponyrt/asio/emscripten.c
  src/libponyrt/asio/epoll.c
  src/libponyrt/asio/event.c
  src/libponyrt/asio/iocp.c
  src/libponyrt/asio/kqueue.c
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
Labels: discuss during sync

#4648 Make pony assertions print backtraces on macos
  src/libponyrt/platform/ponyassert.c
Labels: discuss during sync

#4647 Make sure systematic testing doesn't switch to suspended thread
  .release-notes/4647.md
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
  src/libponyrt/sched/systematic_testing.c
Labels: changelog - fixed, discuss during sync

#4650 Allow running CI test stress manually
  .github/workflows/stress-test-runtime.yml
Labels: discuss during sync

#4653 Fix "not really failing" Windows stress tests
  make.ps1
Labels: discuss during sync

#4656 Fix lack of space in stress test error message
  .github/workflows/stress-test-tcp-open-close-linux.yml
  .github/workflows/stress-test-ubench-linux.yml
Labels: discuss during sync

#4658 Fix race condition in epoll ASIO system
  .release-notes/asio-race.md
  src/libponyrt/asio/epoll.c
  src/libponyrt/asio/iocp.c
  src/libponyrt/asio/kqueue.c
Labels: changelog - fixed, discuss during sync

#4622 Make pony programs exit on an unrecognized pony runtime option
  src/libponyrt/options/options.c
Labels: changelog - changed, discuss during sync

#4649 Add ability to trace runtime events in chromium json format
  .github/workflows/pr.yml
  .release-notes/4649.md
  CMakeLists.txt
  Makefile
  src/libponyc/ast/ast.c
  src/libponyc/ast/source.c
  src/libponyc/ast/stringtab.c
  src/libponyc/ast/symtab.c
  src/libponyc/ast/token.c
  src/libponyc/codegen/codegen.c
  src/libponyc/codegen/codegen.h
  src/libponyc/codegen/gendesc.c
  src/libponyc/codegen/genexe.c
  src/libponyc/codegen/genfun.c
  src/libponyc/codegen/genname.c
  src/libponyc/codegen/genname.h
  src/libponyc/codegen/gentype.c
  src/libponyc/codegen/gentype.h
  src/libponyc/pkg/package.c
  src/libponyc/pkg/program.c
  src/libponyc/reach/reach.c
  src/libponyc/type/reify.c
  src/libponyrt/CMakeLists.txt
  src/libponyrt/actor/actor.c
  src/libponyrt/actor/actor.h
  src/libponyrt/asio/epoll.c
  src/libponyrt/asio/iocp.c
  src/libponyrt/asio/kqueue.c
  src/libponyrt/ds/hash.h
  src/libponyrt/ds/list.h
  src/libponyrt/gc/cycle.c
  src/libponyrt/gc/cycle.h
  src/libponyrt/options/options.h
  src/libponyrt/pony.h
  src/libponyrt/sched/cpu.c
  src/libponyrt/sched/cpu.h
  src/libponyrt/sched/scheduler.c
  src/libponyrt/sched/scheduler.h
  src/libponyrt/sched/start.c
  src/libponyrt/sched/systematic_testing.c
  src/libponyrt/tracing/tracing.c
  src/libponyrt/tracing/tracing.h
  test/libponyrt/ds/hash.cc
Labels: changelog - added, discuss during sync

#4661 Enhance scheduler message tracing with message ids
  .release-notes/4661.md
  src/libponyrt/sched/scheduler.c
  src/libponyrt/tracing/tracing.c
  src/libponyrt/tracing/tracing.h
Labels: discuss during sync

#4664 Fix user-after-free in actor run stop tracing events
  src/libponyrt/actor/actor.c
  src/libponyrt/sched/scheduler.c
Labels: discuss during sync

#4665 Allow setting the number of times we run an open/close stress test
  .github/workflows/stress-test-tcp-open-close-macos.yml
  Makefile
Labels: discuss during sync

#4667 Use opaque pointers in tracing structs to prevent accidental derefs
  src/libponyrt/tracing/tracing.c
Labels: discuss during sync

#4668 Properly free message in flight recorder dump logic
  src/libponyrt/tracing/tracing.c
Labels: discuss during sync

#4671 Add new tracing event for when an actor behavior run is scheduled
  src/libponyrt/actor/actor.c
  src/libponyrt/tracing/tracing.c
  src/libponyrt/tracing/tracing.h
Labels: discuss during sync

#4672 Make tracing flight recorder crash timestamp more accurate
  src/libponyrt/tracing/tracing.c
Labels: discuss during sync

#4674 Don't force tracing flight recorder output to stderr anymore
  src/libponyrt/options/options.h
  src/libponyrt/tracing/tracing.c
Labels: discuss during sync

#4675 Tracing clock_gettime_nsec_np is in nanos so don't divide by 1000
  src/libponyrt/tracing/tracing.c
Labels: discuss during sync

#4669 Add created by actor for actor created tracing event
  src/libponyrt/tracing/tracing.c
Labels: discuss during sync

#4673 Add missing quotes to tracing flight recorder fatal signal event
  src/libponyrt/tracing/tracing.c
Labels: discuss during sync

#4676 Use atomics for tracing flight recorder events
  src/libponyrt/tracing/tracing.c
Labels: discuss during sync

#4670 Add msg_id to tracing actor behavior run start and stop events
  src/libponyrt/actor/actor.c
  src/libponyrt/tracing/tracing.c
  src/libponyrt/tracing/tracing.h
Labels: discuss during sync
