Repository ponylang/ponyc, pull requests merged in 2025-05, with the labels that each got.

#4703 Set explicit linker when testing 32 bit cross compiled architectures
  .github/workflows/pr.yml
Labels: discuss during sync

#4704 Don't set gold as the default ponyc linker on Linux
  .release-notes/gold.md
  src/libponyc/codegen/genexe.c
Labels: changelog - changed, discuss during sync

#4700 Remove experimental label from `--static` compiler option
  src/libponyc/options/options.c
Labels: discuss during sync

#4706 Add aarch64 linux musl nightly builds
  .ci-scripts/aarch64-nightly.bash
  .github/workflows/nightlies.yml
Labels: discuss during sync

#4692 Add CI testing for Linux Aarch64 using musl
  .ci-dockerfiles/aarch64-unknown-linux-musl-builder/Dockerfile
  .ci-dockerfiles/aarch64-unknown-linux-musl-builder/build-and-push.bash
  .github/workflows/pr.yml
  .github/workflows/stress-test-tcp-open-close-linux.yml
  .github/workflows/stress-test-ubench-linux.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4709 Add Alpine 3.20 as a supported platform
  .ci-dockerfiles/x86-64-unknown-linux-alpine3.20-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-alpine3.20-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/release.yml
  .release-notes/alpine3.20.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4710 Add Alpine 3.21 as a supported platform
  .ci-dockerfiles/x86-64-unknown-linux-alpine3.21-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-alpine3.21-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/release.yml
  .release-notes/alpine-3.21.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4711 Rename musl arm64
  .ci-dockerfiles/arm64-unknown-linux-alpine3.20-builder/Dockerfile
  .ci-dockerfiles/arm64-unknown-linux-alpine3.20-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/stress-test-tcp-open-close-linux.yml
  .github/workflows/stress-test-ubench-linux.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4712 Make Alpine 3.21 the default Alpine for arm64 version
  .github/workflows/pr.yml
  .github/workflows/stress-test-tcp-open-close-linux.yml
  .github/workflows/stress-test-ubench-linux.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4713 Rename aarch64 Ubuntu 24.04 to arm64 Ubuntu 24.04
  .ci-dockerfiles/arm64-unknown-linux-ubuntu24.04-builder/Dockerfile
  .ci-dockerfiles/arm64-unknown-linux-ubuntu24.04-builder/build-and-push.bash
  .github/workflows/pr.yml
  .github/workflows/stress-test-tcp-open-close-linux.yml
  .github/workflows/stress-test-ubench-linux.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4714 Add Ubuntu 24.04 on arm64 as a supported platform
  .github/workflows/nightlies.yml
  .github/workflows/release.yml
  .release-notes/ubuntu24-arm.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4715 Drop Alpine 3.20 on arm64 testing
  .ci-dockerfiles/arm64-unknown-linux-alpine3.20-builder/Dockerfile
  .ci-dockerfiles/arm64-unknown-linux-alpine3.20-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4716 Add Alpine 3.21 on arm64 as a supported platform
  .github/workflows/release.yml
  .release-notes/alpine-321-arm.md
  RELEASE_PROCESS.md
Labels: changelog - added, discuss during sync

#4717 Use more appropriate arch when doing arm64 builds
  .ci-scripts/arm64-nightly.bash
  .ci-scripts/arm64-release.bash
Labels: discuss during sync

#4707 Update GoogleTest version to 1.17.0
  lib/CMakeLists.txt
Labels: discuss during sync

#4718 Add additional builders to our lib update workflow
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4719 Add arm64 musl nightly image
  .dockerfiles/latest/arm64-unknown-linux-musl/Dockerfile
  .dockerfiles/latest/arm64-unknown-linux-musl/build-and-push.bash
  .github/workflows/cloudsmith-package-sychronised.yml
  .github/workflows/pr.yml
Labels: do not merge, discuss during sync

#4689 Support building ponyc natively on arm64 Windows machines
  .github/workflows/pr.yml
  .release-notes/4689.md
  make.ps1
  src/common/platform.h
  src/common/pony/detail/atomics.h
  src/libponyc/CMakeLists.txt
  src/libponyc/codegen/genexe.c
  src/libponyc/platform/vcvars.c
  src/libponyrt/lang/directory.c
  src/libponyrt/lang/win_except.c
  src/libponyrt/platform/ponyassert.c
  src/libponyrt/sched/cpu.c
Labels: do not merge, changelog - added, discuss during sync

#4722 Make the check for Visual Studio more robust
  .release-notes/4722.md
  src/libponyc/platform/vcvars.c
Labels: changelog - fixed, discuss during sync

#4723 Add sending an event when the linux arm64 image is update nightly
  .github/workflows/cloudsmith-package-sychronised.yml
Labels: discuss during sync

#4724 Pin buildx for arm to specific version
  .github/workflows/cloudsmith-package-sychronised.yml
Labels: discuss during sync

#4727 Update Dockerfiles to use new ENV format
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu24.04-builder/Dockerfile
  .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
  .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
  .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
  .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
Labels: discuss during sync

#4726 Fix linking on Linux arm64 when using musl libc
  .release-notes/musl-link.md
  src/libponyc/codegen/genexe.c
Labels: changelog - fixed, discuss during sync

#4728 Add corral to arm64 alpine latest image
  .dockerfiles/latest/arm64-unknown-linux-musl/Dockerfile
Labels: discuss during sync
