Repository ponylang/ponyc, pull requests merged in 2025-04, with the labels that each got.

#4666 Prevent memory explosion when using ponynoblock in some programs
  .release-notes/4666.md
  src/libponyrt/actor/actor.c
Labels: changelog - fixed, discuss during sync

#4662 Make GC for an actor more aggressive if an actor GC frees many refs
  .release-notes/4662.md
  src/libponyrt/actor/actor.c
  src/libponyrt/mem/heap.c
  src/libponyrt/mem/heap.h
  test/libponyrt/mem/heap.cc
Labels: do not merge, changelog - fixed, discuss during sync

#4678 Update to using MacOS 15 for all CI
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-tcp-open-close-macos.yml
  .github/workflows/stress-test-ubench-macos.yml
  .github/workflows/update-lib-cache.yml
Labels: discuss during sync

#4679 Fix libc++ compatibility
  src/libponyc/CMakeLists.txt
  src/ponyc/CMakeLists.txt
Labels: discuss during sync

#4683 Add partial support for Windows on Arm64
  .github/actionlint.yaml
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
Labels: discuss during sync

#4684 Fix incorrect package name when doing windows arm builds
  .github/workflows/nightlies.yml
  .github/workflows/release.yml
  make.ps1
Labels: discuss during sync

#4688 Turn off "arm64 windows partial support"
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
Labels: discuss during sync

#4694 Set test runner max parallelism to 1
  Makefile
Labels: do not merge, discuss during sync

#4693 Drop Ubuntu 20.04 Support
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/Dockerfile
  .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/build-and-push.bash
  .github/workflows/nightlies.yml
  .github/workflows/release.yml
  .github/workflows/update-lib-cache.yml
  .release-notes/u20-eol.md
  INSTALL.md
  RELEASE_PROCESS.md
Labels: changelog - changed, discuss during sync

#4696 Remove no longer needed LLVM patch to support newer Alpine versions
  lib/llvm/patches/.keep
  lib/llvm/patches/llvm15-musl-lseek64.diff
Labels: discuss during sync

#4698 Make sure LLVM patch directory changes are caught despite caching
  .github/workflows/nightlies.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stress-test-tcp-open-close-linux.yml
  .github/workflows/stress-test-tcp-open-close-macos.yml
  .github/workflows/stress-test-tcp-open-close-windows.yml
  .github/workflows/stress-test-ubench-linux.yml
  .github/workflows/stress-test-ubench-macos.yml
  .github/workflows/stress-test-ubench-windows.yml
  .github/workflows/update-lib-cache.yml
  lib/CMakeLists.txt
Labels: discuss during sync

#4699 Patch LLVM 17 to work with GCC 15
  lib/CMakeLists.txt
  lib/llvm/patches/2025-04-30-gcc-15.diff
Labels: discuss during sync
